module.exports = {
   'SBIS3.UNITTEST.HomePage': '/billing/python-tools/Testing Cloud/client/HomePage/components/HomePage/HomePage.module.js',
   'SBIS3.Contragents.AdminConfig': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/Admin/Config/AdminConfig.module.js',
   'SBIS3.BUH.KASSA.cashOtherDocuments.Dialog': '/buh/money/client/Money/deprecated/cashOtherDocDialog.module.js',
   'SBIS3.Contragents.ActivOKVEDChoose': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/ActivOKVEDChoose/ActivOKVEDChoose.module.js',
   'SBIS3.Contragents.ContragentCardExtracts': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/ContragentCardExtracts/ContragentCardExtracts.module.js',
   'SBIS3.Contragents.Admin': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/Admin/Admin.module.js',
   'SBIS3.Contragents.ContragentCardPanelTabs': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/ContragentCardPanelTabs/ContragentCardPanelTabs.module.js',
   'SBIS3.Contragents.ContragentChoice': '/root/sbis3-tender/tenderext-service/client/TenderExtUI/cap_modules/ContragentChoice/ContragentChoice.module.js',
   'SBIS3.Contragents.ContragentListFilter': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/ContragentListFilter/ContragentListFilter.module.js',
   'SBIS3.Contragents.ContragentSPPCommonFunctions': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/ContragentSPPCommonFunctions/ContragentSPPCommonFunctions.module.js',
   'SBIS3.Contragents.CourtsChoose': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/CourtsChoose/CourtsChoose.module.js',
   'SBIS3.Contragents.CourtStatistics': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/CourtStatistics/CourtStatistics.module.js',
   'SBIS3.Contragents.DialogPhone': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/DialogPhone/DialogPhone.module.js',
   'SBIS3.Contragents.ContragentSPPCardPanel': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/ContragentSPPCardPanel/ContragentSPPCardPanel.module.js',
   'SBIS3.Contragents.DialogResizeLogo': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/DialogResizeLogo/DialogResizeLogo.module.js',
   'SBIS3.Contragents.FiltrCourts': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/FiltrCourts/FiltrCourts.module.js',
   'SBIS3.Contragents.FilterUnloading': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/FilterUnloading/FilterUnloading.module.js',
   'SBIS3.Contragents.FileResult': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/FileResult/FileResult.module.js',
   'SBIS3.Contragents.ContrPageModel': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/FunctionsContrPage/ContrPageModel.module.js',
   'SBIS3.Tender.AddDebtorClassifier': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/IndustryList/EditClassifier/AddDebtorClassifier.module.js',
   'SBIS3.Tender.AddOKDP': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/IndustryList/EditClassifier/AddOKDP.module.js',
   'SBIS3.Tender.AddOKPD': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/IndustryList/EditClassifier/AddOKPD.module.js',
   'SBIS3.Tender.AddOKPD2': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/IndustryList/EditClassifier/AddOKPD2.module.js',
   'SBIS3.Tender.EditClassifier': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/IndustryList/EditClassifier/EditClassifier.module.js',
   'SBIS3.Tender.IndustryList': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/IndustryList/IndustryList.module.js',
   'SBIS3.Contragents.ViewActivities': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/IndustryList/ViewActivities/ViewActivities.module.js',
   'SBIS3.Contragents.LawsuitCardTabs': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/LawsuitCardTabs/LawsuitCardTabs.module.js',
   'SBIS3.Contragents.LicenseMainFilter': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/LicenseMainFilter/LicenseMainFilter.module.js',
   'SBIS3.Contragents.LawsuitCard': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/LawsuitCard/LawsuitCard.module.js',
   'SBIS3.Contragents.LicenseMainListModel': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/LicenseMainList/LicenseMainListModel.module.js',
   'SBIS3.Contragents.CourtsListModel': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/Models/CourtsListModel.module.js',
   'SBIS3.Contragents.ExtractListModel': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/Models/ExtractListModel.module.js',
   'SBIS3.Contragents.UnloadingListModel': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/Models/UnloadingListModel.module.js',
   'SBIS3.Contragents.Parameters': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/Parameters/Parameters.module.js',
   'SBIS3.Contragents.NotificationTemplate': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/NotificationTemplate/NotificationTemplate.module.js',
   'SBIS3.Contragents.ProcessVASSolutionFilter': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/PrcoessVASSolutionFilter/PrcoessVASSolutionFilter.module.js',
   'SBIS3.Contragents.ProcessVASSolutionCard': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/ProcessVASSolutionCard/ProcessVASSolutionCard.module.js',
   'SBIS3.JSR.CompositeView': '/contragents/jobs/client/jobs.sbis.ru/components/common/CompositeView/CompositeView.module.js',
   'SBIS3.JSR.CommonFunctions': '/contragents/jobs/client/jobs.sbis.ru/components/common/CommonFunctions/CommonFunctions.module.js',
   'SBIS3.JSR.DataGridView': '/contragents/jobs/client/jobs.sbis.ru/components/common/DataGridView/DataGridView.module.js',
   'SBIS3.Contragents.WorkWithCache': '/contragents/admin-spp/UI/SPPAdministration/SPPManagment/components/WorkWithCache/WorkWithCache.module.js',
   'SBIS3.JSR.Dialogs.RegionDialog': '/contragents/jobs/client/jobs.sbis.ru/components/common/Dialogs/RegionDialog/RegionDialog.module.js',
   'SBIS3.JSR.Dialogs.CategoryDialog': '/contragents/jobs/client/jobs.sbis.ru/components/common/Dialogs/CategoryDialog/CategoryDialog.module.js',
   'SBIS3.JSR.VacanciesSubscriptionDialog': '/contragents/jobs/client/jobs.sbis.ru/components/common/Dialogs/VacanciesSubscriptionDialog/VacanciesSubscriptionDialog.module.js',
   'SBIS3.JSR.DropdownList': '/contragents/jobs/client/jobs.sbis.ru/components/common/DropdownList/DropdownList.module.js',
   'SBIS3.JSR.DSManager': '/contragents/jobs/client/jobs.sbis.ru/components/common/DSManager/DSManager.module.js',
   'SBIS3.JSR.Footer': '/contragents/jobs/client/jobs.sbis.ru/components/common/Footer/Footer.module.js',
   'SBIS3.JSR.FilterPanelUtils': '/contragents/jobs/client/jobs.sbis.ru/components/common/FilterPanelUtils/FilterPanelUtils.module.js',
   'SBIS3.JSR.GoToPageBtn': '/contragents/jobs/client/jobs.sbis.ru/components/common/GoToPageBtn/GoToPageBtn.module.js',
   'SBIS3.JSR.JSRBrowser': '/contragents/jobs/client/jobs.sbis.ru/components/common/JSRBrowser/JSRBrowser.module.js',
   'SBIS3.JSR.Header': '/contragents/jobs/client/jobs.sbis.ru/components/common/Header/Header.module.js',
   'SBIS3.JSR.JSRBrowser.Companies': '/contragents/jobs/client/jobs.sbis.ru/components/common/JSRBrowser/resources/Companies/Companies.module.js',
   'SBIS3.JSR.Header.SearchSelector': '/contragents/jobs/client/jobs.sbis.ru/components/common/Header/resources/SearchSelector/SearchSelector.module.js',
   'SBIS3.JSR.JSRBrowser.Toolbar': '/contragents/jobs/client/jobs.sbis.ru/components/common/JSRBrowser/resources/Toolbar/Toolbar.module.js',
   'SBIS3.JSR.KLADRUtils': '/contragents/jobs/client/jobs.sbis.ru/components/common/KLADRUtils/KLADRUtils.module.js',
   'SBIS3.JSR.ModelUtils': '/contragents/jobs/client/jobs.sbis.ru/components/common/ModelUtils/ModelUtils.module.js',
   'SBIS3.JSR.MasterPageBase': '/contragents/jobs/client/jobs.sbis.ru/components/common/MasterPageBase/MasterPageBase.module.js',
   'SBIS3.JSR.RegionSelectorLink': '/contragents/jobs/client/jobs.sbis.ru/components/common/RegionSelectorLink/RegionSelectorLink.module.js',
   'SBIS3.JSR.ScrollWatcher': '/contragents/jobs/client/jobs.sbis.ru/components/common/ScrollWatcher/ScrollWatcher.module.js',
   'SBIS3.JSR.SearchForm': '/contragents/jobs/client/jobs.sbis.ru/components/common/SearchForm/SearchForm.module.js',
   'SBIS3.JSR.SubscriptionButton': '/contragents/jobs/client/jobs.sbis.ru/components/common/SubscriptionButton/SubscriptionButton.module.js',
   'SBIS3.JSR.Types.Dictionary': '/contragents/jobs/client/jobs.sbis.ru/components/common/Types/Dictionary/Dictionary.module.js',
   'SBIS3.JSR.VacancyList': '/contragents/jobs/client/jobs.sbis.ru/components/common/VacancyList/VacancyList.module.js',
   'SBIS3.JSR.VacancyTile': '/contragents/jobs/client/jobs.sbis.ru/components/common/VacancyTile/VacancyTile.module.js',
   'SBIS3.JSR.Companies': '/contragents/jobs/client/jobs.sbis.ru/components/Companies/Companies.module.js',
   'SBIS3.JSR.Companies.Aggregator': '/contragents/jobs/client/jobs.sbis.ru/components/Companies/resources/Aggregator/Aggregator.module.js',
   'SBIS3.JSR.Companies.CompanyList': '/contragents/jobs/client/jobs.sbis.ru/components/Companies/resources/CompanyList/CompanyList.module.js',
   'SBIS3.JSR.Company': '/contragents/jobs/client/jobs.sbis.ru/components/Company/Company.module.js',
   'SBIS3.JSR.Company.VacancyListToCategories': '/contragents/jobs/client/jobs.sbis.ru/components/Company/resources/VacancyListToCategories/VacancyListToCategories.module.js',
   'SBIS3.JSR.Index': '/contragents/jobs/client/jobs.sbis.ru/components/Index/Index.module.js',
   'SBIS3.JSR.Company.Description': '/contragents/jobs/client/jobs.sbis.ru/components/Company/resources/Description/Description.module.js',
   'SBIS3.JSR.Index.Categories': '/contragents/jobs/client/jobs.sbis.ru/components/Index/resources/Categories/Categories.module.js',
   'SBIS3.JSR.Index.Banner': '/contragents/jobs/client/jobs.sbis.ru/components/Index/resources/Banner/Banner.module.js',
   'SBIS3.JSR.Vacancies': '/contragents/jobs/client/jobs.sbis.ru/components/Vacancies/Vacancies.module.js',
   'SBIS3.JSR.Vacancies.Aggregator': '/contragents/jobs/client/jobs.sbis.ru/components/Vacancies/resources/Aggregator/Aggregator.module.js',
   'SBIS3.JSR.Vacancy': '/contragents/jobs/client/jobs.sbis.ru/components/Vacancy/Vacancy.module.js',
   'SBIS3.JSR.CompaniesMasterPage': '/contragents/jobs/client/jobs.sbis.ru/masterPages/CompaniesMasterPage.module.js',
   'SBIS3.JSR.CompanyMasterPage': '/contragents/jobs/client/jobs.sbis.ru/masterPages/CompanyMasterPage.module.js',
   'SBIS3.JSR.VacanciesMasterPage': '/contragents/jobs/client/jobs.sbis.ru/masterPages/VacanciesMasterPage.module.js',
   'SBIS3.JSR.VacancyMasterPage': '/contragents/jobs/client/jobs.sbis.ru/masterPages/VacancyMasterPage.module.js',
   'SBIS3.JSR.IndexMasterPage': '/contragents/jobs/client/jobs.sbis.ru/masterPages/IndexMasterPage.module.js',
   'SBIS3.JSR.BindEventsToWindowMixin': '/contragents/jobs/client/jobs.sbis.ru/mixins/BindEventsToWindowMixin.module.js',
   'SBIS3.JSR.ScrollWatcherMixin': '/contragents/jobs/client/jobs.sbis.ru/mixins/ScrollWatcherMixin.module.js',
   'SBIS3.JSR.TotalStatisticMixin': '/contragents/jobs/client/jobs.sbis.ru/mixins/TotalStatisticMixin.module.js',
   'SBIS3.JSR.CompanyModel': '/contragents/jobs/client/jobs.sbis.ru/models/CompanyModel.module.js',
   'SBIS3.JSR.View': '/contragents/jobs/client/Theme/View/View.module.js',
   'SBIS3.JSR.VacancyModel': '/contragents/jobs/client/jobs.sbis.ru/models/VacancyModel.module.js',
   'SBIS3.NAVIGATION.DocumentSwap': '/edo/core/client/Document exchange/navigation/DocumentSwapNavigation.module.js',
   'SBIS3.EDO.Photo': '/usermngt/personal-office/client/Личный аккаунт/Fixes/Photo-fix.module.js',
   'SBIS3.Staff.Choice': '/usermngt/personal-office/client/Личный аккаунт/Fixes/Choice/Choice-fix.module.js',
   'SBIS3.EDO.FormatDocumentEditor': '/edo/docs-external-processing/docs-ext-proc/client/Внешняя работа с документом/FormatDocumentEditor/FormatDocumentEditor.module.js',
   'SBIS3.EDO.FormatDocumentEditorHandlers': '/edo/docs-external-processing/docs-ext-proc/client/Внешняя работа с документом/FormatDocumentEditor/FormatDocumentEditorHandlers.module.js',
   'SBIS3.SVRD.Index': '/edo/docs-external-processing/docs-ext-proc/client/Внешняя работа с документом/Index/Index.module.js',
   'SBIS3.INVITES.ChooserPanel': '/edo/docs-external-processing/invites/client/InvitesTemplate/Template/ChooserPanel.module.js',
   'SBIS3.Site.EntryView': '/edo/docs-external-processing/docs-ext-proc/client/Внешняя работа с документом/EntryView/EntryView.module.js',
   'SBIS3.INVITES.InviteDocViewFooter': '/edo/docs-external-processing/invites/client/InvitesTemplate/Template/InviteDocViewFooter.module.js',
   'SBIS3.INVITES.InviteDocViewHeader': '/edo/docs-external-processing/invites/client/InvitesTemplate/Template/InviteDocViewHeader.module.js',
   'SBIS3.INVITES.RegionChooser': '/edo/docs-external-processing/invites/client/InvitesTemplate/Template/RegionChooser.module.js',
   'SBIS3.INVITES.RegionManager': '/edo/docs-external-processing/invites/client/InvitesTemplate/Template/RegionManager.module.js',
   'SBIS3.Analytics.QuarantineEdit': '/eo/analytics/client-adm/Администрирование сервиса АБ/Управление сервисом АБ/components/Quarantine/Edit/QurantineEdit.module.js',
   'SBIS3.Analytics.AdminConfig': '/eo/analytics/client-adm/Администрирование сервиса АБ/Управление сервисом АБ/components/Admin/Config/AdminConfig.module.js',
   'SBIS3.Analytics.QuarantineFilter': '/eo/analytics/client-adm/Администрирование сервиса АБ/Управление сервисом АБ/components/Quarantine/Filter/QuarantineFilter.module.js',
   'SBIS3.Analytics.Admin': '/eo/analytics/client-adm/Администрирование сервиса АБ/Управление сервисом АБ/components/Admin/Admin.module.js',
   'SBIS3.Analytics.Quarantine': '/eo/analytics/client-adm/Администрирование сервиса АБ/Управление сервисом АБ/components/Quarantine/Quarantine.module.js',
   'SBIS3.Analytics.QueueEdit': '/eo/analytics/client-adm/Администрирование сервиса АБ/Управление сервисом АБ/components/Queue/Edit/QueueEdit.module.js',
   'SBIS3.Analytics.QueueFilter': '/eo/analytics/client-adm/Администрирование сервиса АБ/Управление сервисом АБ/components/Queue/Filter/QueueFilter.module.js',
   'SBIS3.Analytics.QueueNewTask': '/eo/analytics/client-adm/Администрирование сервиса АБ/Управление сервисом АБ/components/Queue/NewTask/QueueNewTask.module.js',
   'SBIS3.Analytics.Settings': '/eo/analytics/client-adm/Администрирование сервиса АБ/Управление сервисом АБ/components/Settings/Settings.module.js',
   'SBIS3.Analytics.StatisticsFilter': '/eo/analytics/client-adm/Администрирование сервиса АБ/Управление сервисом АБ/components/Statistics/Filter/StatisticsFilter.module.js',
   'SBIS3.Analytics.Queue': '/eo/analytics/client-adm/Администрирование сервиса АБ/Управление сервисом АБ/components/Queue/Queue.module.js',
   'SBIS3.Analytics.VisitFilter': '/eo/analytics/client-adm/Администрирование сервиса АБ/Управление сервисом АБ/components/Visit/Filter/VisitFilter.module.js',
   'SBIS3.Analytics.Statistics': '/eo/analytics/client-adm/Администрирование сервиса АБ/Управление сервисом АБ/components/Statistics/Statistics.module.js',
   'SBIS3.Analytics.Visit': '/eo/analytics/client-adm/Администрирование сервиса АБ/Управление сервисом АБ/components/Visit/Visit.module.js',
   'SBIS3.DemoCode.FieldCalculatedDemo': '/fed/core/client/demo/FED/FieldCalculatedDemo/FieldCalculatedDemo.module.js',
   'SBIS3.DemoCode.RollingAreaDemo': '/fed/core/client/demo/FED/RollingAreaDemo/RollingAreaDemo.module.js',
   'SBIS3.DemoCode.SquareFieldStringDemo': '/fed/core/client/demo/FED/SquareFieldStringDemo/SquareFieldStringDemo.module.js',
   'Test.SBIS3.FED2.ND_ENVD': '/fed/core/client/test/FED2/ND_ENVD/ND_ENVD.module.js',
   'SBIS3.FORM.TestForm_02914015_1': '/fed/specifications/test/Спецификации ФЭД (компоненты)/FNS/Testing/1/TestForm_02914015_1/TestForm_02914015_1.module.js',
   'SBIS3.Test.Index': '/fed/models/client/ModelsUI/Index/Index.module.js',
   'SBIS3.IntegrationConfig.SynchronizationHistory': '/integration/config/client/IntegrationConfig/Comparison/components/SynchronizationHistory/SynchronizationHistory.module.js',
   'SBIS3.IntegrationConfig.SynchronizationHistoryErrors': '/integration/config/client/IntegrationConfig/Comparison/components/SynchronizationHistoryReport/SynchronizationHistoryErrors/SynchronizationHistoryErrors.module.js',
   'SBIS3.IntegrationConfig.SynchronizationHistoryObjects': '/integration/config/client/IntegrationConfig/Comparison/components/SynchronizationHistoryReport/SynchronizationHistoryObjects/SynchronizationHistoryObjects.module.js',
   'SBIS3.IntegrationConfig.SynchronizationHistoryReport': '/integration/config/client/IntegrationConfig/Comparison/components/SynchronizationHistoryReport/SynchronizationHistoryReport.module.js',
   'SBIS3.IntegrationConfig.ErrorDialog': '/integration/config/client/IntegrationConfig/Dialogs/ErrorDialog/ErrorDialog.module.js',
   'SBIS3.IntegrationConfig.FilterErrorsTemplate': '/integration/config/client/IntegrationConfig/Dialogs/FilterErrorsTemplate/FilterErrorsTemplate.module.js',
   'SBIS3.IntegrationConfig.FilterLineErrorTemplate': '/integration/config/client/IntegrationConfig/Dialogs/FilterLineErrorTemplate/FilterLineErrorTemplate.module.js',
   'SBIS3.IntegrationConfig.FilterStatisticTemplate': '/integration/config/client/IntegrationConfig/Dialogs/FilterStatisticTemplate/FilterStatisticTemplate.module.js',
   'SBIS3.IntegrationConfig.FilterLineStatTemplate': '/integration/config/client/IntegrationConfig/Dialogs/FilterLineStatTemplate/FilterLineStatTemplate.module.js',
   'SBIS3.IntegrationConfig.DisconnectedAccounts': '/integration/config/client/IntegrationConfig/MainPage/DisconnectedAccounts/DisconnectedAccounts.module.js',
   'SBIS3.IntegrationConfig.SendMessage': '/integration/config/client/IntegrationConfig/Dialogs/SendMessage/SendMessage.module.js',
   'SBIS3.IntegrationConfig.Errors': '/integration/config/client/IntegrationConfig/MainPage/Errors/Errors.module.js',
   'SBIS3.IntegrationConfig.ErrorsListByMessage': '/integration/config/client/IntegrationConfig/MainPage/ErrorsListByMessage/ErrorsListByMessage.module.js',
   'SBIS3.IntegrationConfig.ErrorsListByAccount': '/integration/config/client/IntegrationConfig/MainPage/ErrorsListByAccount/ErrorsListByAccount.module.js',
   'SBIS3.IntegrationConfig.ProblemAccountsTable': '/integration/config/client/IntegrationConfig/MainPage/ProblemAccountsTable/ProblemAccountsTable.module.js',
   'SBIS3.IntegrationConfig.ProblemActions': '/integration/config/client/IntegrationConfig/MainPage/ProblemActions/ProblemActions.module.js',
   'SBIS3.IntegrationConfig.Stat': '/integration/config/client/IntegrationConfig/MainPage/Stat/Stat.module.js',
   'SBIS3.IntegrationConfig.StatisticDetails': '/integration/config/client/IntegrationConfig/MainPage/StatisticDetails/StatisticDetails.module.js',
   'SBIS3.IntegrationConfig.StatisticListByAccount': '/integration/config/client/IntegrationConfig/MainPage/StatisticListByAccount/StatisticListByAccount.module.js',
   'SBIS3.IntegrationConfig.TestCom': '/integration/config/client/IntegrationConfig/MainPage/TestCom/TestCom.module.js',
   'SBIS3.Plugin.Source.Provider.SbisPlugin': '/integration/config/client/SBIS3.Plugin/components/Source/Provider/SbisPlugin.module.js',
   'SBIS3.Plugin.Source.LocalService': '/integration/config/client/SBIS3.Plugin/components/Source/LocalService.module.js',
   'SBIS3.Plugin.Source.Provider.SbisPlugin.Connector': '/integration/config/client/SBIS3.Plugin/components/Source/Provider/SbisPlugin/Connector/Connector.module.js',
   'SBIS3.Plugin.Source.Provider.SbisPlugin.Initializer': '/integration/config/client/SBIS3.Plugin/components/Source/Provider/SbisPlugin/Connector/Initializer.module.js',
   'SBIS3.Plugin.Source.Provider.SbisPlugin.Helper': '/integration/config/client/SBIS3.Plugin/components/Source/Provider/SbisPlugin/Helper.module.js',
   'SBIS3.Plugin.Source.Provider.SbisPlugin.PluginLoadDialog': '/integration/config/client/SBIS3.Plugin/components/Source/Provider/SbisPlugin/PluginLoadDialog/PluginLoadDialog.module.js',
   'SBIS3.Plugin.Source.Provider.SbisPlugin.PluginSetupDialog': '/integration/config/client/SBIS3.Plugin/components/Source/Provider/SbisPlugin/PluginSetupDialog/PluginSetupDialog.module.js',
   'SBIS3.Plugin.Source.SbisPluginProvider': '/integration/config/client/SBIS3.Plugin/components/Source/SbisPluginProvider.module.js',
   'SBIS3.DESKTOP.Source.SbisPluginService': '/integration/config/client/SBIS3.Plugin/components/Source/SbisPluginService.module.js',
   'SBIS3.Plugin.Source.Provider.SbisPluginManager': '/integration/config/client/SBIS3.Plugin/components/Source/Provider/SbisPluginManager.module.js',
   'SBIS3.TaskQueue.AccordionConfig': '/plugin-task-queue/service/client/task-queue-diagnostics/AccordionConfig.module.js',
   'SBIS3.TaskQueue.Index': '/plugin-task-queue/service/client/task-queue-diagnostics/Index/Index.module.js',
   'SBIS3.TaskQueue.TaskRegistry.Model': '/plugin-task-queue/service/client/task-queue-diagnostics/TaskRegistry/Model/Model.module.js',
   'SBIS3.TaskQueue.TaskRegistry.Filter': '/plugin-task-queue/service/client/task-queue-diagnostics/TaskRegistry/Filter/Filter.module.js',
   'SBIS3.TaskQueue.Task.Dialog': '/plugin-task-queue/service/client/task-queue-diagnostics/TaskRegistry/Dialog/Dialog.module.js',
   'SBIS3.TaskQueue.TaskRegistry': '/plugin-task-queue/service/client/task-queue-diagnostics/TaskRegistry/TaskRegistry.module.js',
   'SBIS3.NAVIGATION.ConfigPrint': '/printforms/html-converter/client/SettingsConverting/ConfigPrint.module.js',
   'SBIS3.Plugin.Source.ServiceManager': '/integration/config/client/SBIS3.Plugin/components/Source/ServiceManager.module.js',
   'SBIS3.Index_help': '/root/help-sbis-ru/Модули/HelpEditor/Index_help/Index_help.module.js',
   'SBIS3.Help.TplDoc': '/root/help-sbis-ru/Модули/HelpViewer/TplDoc/TplDoc.module.js',
   'SBIS3.Help.Claim': '/root/help-sbis-ru/Модули/HelpViewer/TplIndex/resources/Claim/Claim.module.js',
   'SBIS3.Help.ClaimSendNotice': '/root/help-sbis-ru/Модули/HelpViewer/TplIndex/resources/ClaimSendNotice/ClaimSendNotice.module.js',
   'SBIS3.Help.TplIndex': '/root/help-sbis-ru/Модули/HelpViewer/TplIndex/TplIndex.module.js',
   'SBIS3.Help.TplSearchResult': '/root/help-sbis-ru/Модули/HelpViewer/TplSearchResult/TplSearchResult.module.js',
   'SBIS3.Help.StaffReportBrowse': '/root/help-sbis-ru/Модули/HelpViewer/TplStaff/resources/StaffReportBrowse/StaffReportBrowse.module.js',
   'SBIS3.Help.StaffReportBrowseCommon': '/root/help-sbis-ru/Модули/HelpViewer/TplStaff/resources/StaffReportBrowseCommon/StaffReportBrowseCommon.module.js',
   'SBIS3.Help.StaffReportClaim': '/root/help-sbis-ru/Модули/HelpViewer/TplStaff/resources/StaffReportClaim/StaffReportClaim.module.js',
   'SBIS3.Help.StaffReportDislike': '/root/help-sbis-ru/Модули/HelpViewer/TplStaff/resources/StaffReportDislike/StaffReportDislike.module.js',
   'SBIS3.Help.StaffReportDislikeCommon': '/root/help-sbis-ru/Модули/HelpViewer/TplStaff/resources/StaffReportDislikeCommon/StaffReportDislikeCommon.module.js',
   'SBIS3.Help.StaffReportFilter': '/root/help-sbis-ru/Модули/HelpViewer/TplStaff/resources/StaffReportFilter/StaffReportFilter.module.js',
   'SBIS3.Help.StaffReportFilterClaim': '/root/help-sbis-ru/Модули/HelpViewer/TplStaff/resources/StaffReportFilterClaim/StaffReportFilterClaim.module.js',
   'SBIS3.Help.StaffReportFilterCommon': '/root/help-sbis-ru/Модули/HelpViewer/TplStaff/resources/StaffReportFilterCommon/StaffReportFilterCommon.module.js',
   'SBIS3.Help.StaffReportFilterExt': '/root/help-sbis-ru/Модули/HelpViewer/TplStaff/resources/StaffReportFilterExt/StaffReportFilterExt.module.js',
   'SBIS3.Help.StaffReportFilterSearch': '/root/help-sbis-ru/Модули/HelpViewer/TplStaff/resources/StaffReportFilterSearch/StaffReportFilterSearch.module.js',
   'SBIS3.Help.StaffReportLikeCommon': '/root/help-sbis-ru/Модули/HelpViewer/TplStaff/resources/StaffReportLikeCommon/StaffReportLikeCommon.module.js',
   'SBIS3.Help.StaffReportSearch': '/root/help-sbis-ru/Модули/HelpViewer/TplStaff/resources/StaffReportSearch/StaffReportSearch.module.js',
   'SBIS3.Help.StaffReportLike': '/root/help-sbis-ru/Модули/HelpViewer/TplStaff/resources/StaffReportLike/StaffReportLike.module.js',
   'SBIS3.Help.StaffReportUnusedImages': '/root/help-sbis-ru/Модули/HelpViewer/TplStaff/resources/StaffReportUnusedImages/StaffReportUnusedImages.module.js',
   'SBIS3.Help.TplStaffLogin': '/root/help-sbis-ru/Модули/HelpViewer/TplStaff/resources/TplStaffLogin/TplStaffLogin.module.js',
   'SBIS3.Help.TplStaff': '/root/help-sbis-ru/Модули/HelpViewer/TplStaff/TplStaff.module.js',
   'SBIS3.CLASS.ClassifiersCommonFunc': '/root/sbis3-classifiers/client/Classifiers/ClassifiersLib/lib/CommonFunc.module.js',
   'SBIS3.CLASS.ClassifiersManager': '/root/sbis3-classifiers/client/ClassifiersAdmin/AdminTemplate/Template.module.js',
   'SBIS3.Collation.AdminConfig': '/root/sbis3-collation/client-service/Сервис сверки/components/AdminConfig/AdminConfig.module.js',
   'SBIS3.Collation.AdminPanel': '/root/sbis3-collation/client-service/Сервис сверки/components/AdminPanel/AdminPanel.module.js',
   'SBIS3.Collation.Contragents': '/root/sbis3-collation/client-service/Сервис сверки/components/Contragents/Contragents.module.js',
   'SBIS3.Collation.InvitationAdminPanel': '/root/sbis3-collation/client-service/Сервис сверки/components/Invitations/InvitationAdminPanel/InvitationAdminPanel.module.js',
   'SBIS3.Collation.SynchronizationAdminPanel': '/root/sbis3-collation/client-service/Сервис сверки/components/Synchronization/SynchronizationAdminPanel/SynchronizationAdminPanel.module.js',
   'SBIS3.Collation.TestResult': '/root/sbis3-collation/client-service/Сервис сверки/components/Tests/TestResult/TestResult.module.js',
   'SBIS3.Collation.TestAdminPanel': '/root/sbis3-collation/client-service/Сервис сверки/components/Tests/TestAdminPanel/TestAdminPanel.module.js',
   'SBIS3.Collation.TestAdminPanelHelper': '/root/sbis3-collation/client-service/Сервис сверки/components/TestAdminPanelHelper/TestAdminPanelHelper.module.js',
   'SBIS3.Collation.TestResultByGrid': '/root/sbis3-collation/client-service/Сервис сверки/components/Tests/TestResultByGrid/TestResultByGrid.module.js',
   'SBIS3.CRS.AccordionConfig': '/root/sbis3-cost-recalc/client/CostRecalcConsole/controls/AccordionConfig/AccordionConfig.module.js',
   'SBIS3.CRS.Index': '/root/sbis3-cost-recalc/client/CostRecalcConsole/controls/index/Index.module.js',
   'SBIS3.CRS.CostRecalc': '/root/sbis3-cost-recalc/client/CostRecalcConsole/controls/CostRecalc/CostRecalc.module.js',
   'SBIS3.EGAIS.BL.InDocument': '/root/sbis3-egais/client/EGAIS-diagnostics/BL/InDocument.module.js',
   'SBIS3.EGAIS.BL.Document': '/root/sbis3-egais/client/EGAIS-diagnostics/BL/Document.module.js',
   'SBIS3.EGAIS.BL.OutDocument': '/root/sbis3-egais/client/EGAIS-diagnostics/BL/OutDocument.module.js',
   'SBIS3.EGAIS.BL.UTM': '/root/sbis3-egais/client/EGAIS-diagnostics/BL/UTM.module.js',
   'SBIS3.EGAIS.Index': '/root/sbis3-egais/client/EGAIS-diagnostics/Index/Index.module.js',
   'SBIS3.EGAIS.HungOutDocs.Registry': '/root/sbis3-egais/client/EGAIS-diagnostics/Logs/HungOutDocs/Registry/Registry.module.js',
   'SBIS3.EGAIS.InDocsWithInfo.Dialog': '/root/sbis3-egais/client/EGAIS-diagnostics/Logs/InDocsWithInfo/Dialog/Dialog.module.js',
   'SBIS3.EGAIS.InDocsWithInfo.Registry': '/root/sbis3-egais/client/EGAIS-diagnostics/Logs/InDocsWithInfo/InDocsWithInfo.module.js',
   'SBIS3.EGAIS.OutDocs.Registry': '/root/sbis3-egais/client/EGAIS-diagnostics/Logs/OutDocs/Registry/Registry.module.js',
   'SBIS3.EGAIS.MoveDocument': '/root/sbis3-egais/client/EGAIS-diagnostics/Logs/MoveDocument/MoveDocument.module.js',
   'SBIS3.EGAIS.AccordionConfig': '/root/sbis3-egais/client/EGAIS-diagnostics/AccordionConfig.module.js',
   'SBIS3.EGAIS.OutDocsWithInfo.Dialog': '/root/sbis3-egais/client/EGAIS-diagnostics/Logs/OutDocsWithInfo/Dialog/Dialog.module.js',
   'SBIS3.EGAIS.OutDocsWithInfo.Model': '/root/sbis3-egais/client/EGAIS-diagnostics/Logs/OutDocsWithInfo/Model/Model.module.js',
   'SBIS3.EGAIS.ReadInDocs.Registry': '/root/sbis3-egais/client/EGAIS-diagnostics/Logs/ReadInDocs/Registry/Registry.module.js',
   'SBIS3.EGAIS.OutDocsWithInfo.Registry': '/root/sbis3-egais/client/EGAIS-diagnostics/Logs/OutDocsWithInfo/OutDocsWithInfo.module.js',
   'SBIS3.EGAIS.ReadInDocsResult.Registry': '/root/sbis3-egais/client/EGAIS-diagnostics/Logs/ReadInDocsResult/Registry.module.js',
   'SBIS3.EGAIS.UTM.Registry': '/root/sbis3-egais/client/EGAIS-diagnostics/Logs/UTM/Registry/Registry.module.js',
   'SBIS3.STATPROT.Admin': '/root/sbis3-eo-stat-prot/client/Админка/components/Admin/Admin.module.js',
   'SBIS3.STATPROT.Analyze': '/root/sbis3-eo-stat-prot/client/Админка/components/Analyze/Analyze.module.js',
   'SBIS3.STATPROT.ErrorDetailsTemplate': '/root/sbis3-eo-stat-prot/client/Админка/components/ErrorDetailsTemplate/ErrorDetailsTemplate.module.js',
   'SBIS3.STATPROT.FilterHideContainer': '/root/sbis3-eo-stat-prot/client/Админка/components/ErrorFilter/FilterHideContainer/FilterHideContainer.module.js',
   'SBIS3.STATPROT.ErrorFilterLine': '/root/sbis3-eo-stat-prot/client/Админка/components/ErrorFilter/ErrorFilterLine/ErrorFilterLine.module.js',
   'SBIS3.STATPROT.ErrorFilter': '/root/sbis3-eo-stat-prot/client/Админка/components/ErrorFilter/ErrorFilter.module.js',
   'SBIS3.STATPROT.FilterLinkButtonCtx': '/root/sbis3-eo-stat-prot/client/Админка/components/ErrorFilter/FilterLinkButtonCtx/FilterLinkButtonCtx.module.js',
   'SBIS3.STATPROT.FilterReportPeriod': '/root/sbis3-eo-stat-prot/client/Админка/components/ErrorFilter/FilterReportPeriod/FilterReportPeriod.module.js',
   'SBIS3.EGAIS.ResetFlag.Registry': '/root/sbis3-egais/client/EGAIS-diagnostics/Logs/ResetFlags/ResetFlags.module.js',
   'SBIS3.STATPROT.FilterReportSubType': '/root/sbis3-eo-stat-prot/client/Админка/components/ErrorFilter/FilterReportSubType/FilterReportSubType.module.js',
   'SBIS3.STATPROT.FilterText': '/root/sbis3-eo-stat-prot/client/Админка/components/ErrorFilter/FilterText/FilterText.module.js',
   'SBIS3.STATPROT.SelectReportType': '/root/sbis3-eo-stat-prot/client/Админка/components/ErrorFilter/SelectReportType/SelectReportType.module.js',
   'SBIS3.STATPROT.ErrorList': '/root/sbis3-eo-stat-prot/client/Админка/components/ErrorList/ErrorList.module.js',
   'SBIS3.STATPROT.ErrorListGraph': '/root/sbis3-eo-stat-prot/client/Админка/components/ErrorList/ErrorListGraph/ErrorListGraph.module.js',
   'SBIS3.STATPROT.CreateFolderDialog': '/root/sbis3-eo-stat-prot/client/Админка/components/ErrorsInVersion/CreateFolderDialog/CreateFolderDialog.module.js',
   'SBIS3.STATPROT.ErrorsInVersion': '/root/sbis3-eo-stat-prot/client/Админка/components/ErrorsInVersion/ErrorsInVersion.module.js',
   'SBIS3.STATPROT.ErrorsInVersionGraph': '/root/sbis3-eo-stat-prot/client/Админка/components/ErrorsInVersion/ErrorsInVersionGraph/ErrorsInVersionGraph.module.js',
   'SBIS3.STATPROT.MoveToFolderDialog': '/root/sbis3-eo-stat-prot/client/Админка/components/ErrorsInVersion/MoveToFolderDialog/MoveToFolderDialog.module.js',
   'SBIS3.STATPROT.LeftMenu': '/root/sbis3-eo-stat-prot/client/Админка/components/LeftMenu/LeftMenu.module.js',
   'SBIS3.STATPROT.Helpers': '/root/sbis3-eo-stat-prot/client/Админка/components/Helpers/Helpers.module.js',
   'SBIS3.STATPROT.DocPresentation': '/root/sbis3-eo-stat-prot/client/Админка/components/ProtocolFullViewer/DocPresentation/DocPresentation.module.js',
   'SBIS3.STATPROT.DocumentProtocol': '/root/sbis3-eo-stat-prot/client/Админка/components/ProtocolFullViewer/DocumentProtocol/DocumentProtocol.module.js',
   'SBIS3.STATPROT.FullViewerForProtocol': '/root/sbis3-eo-stat-prot/client/Админка/components/ProtocolFullViewer/FullViewerForProtocol/FullViewerForProtocol.module.js',
   'SBIS3.STATPROT.ViewProtocol': '/root/sbis3-eo-stat-prot/client/Админка/components/ProtocolFullViewer/ViewProtocol/ViewProtocol.module.js',
   'SBIS3.STATPROT.Quarantine': '/root/sbis3-eo-stat-prot/client/Админка/components/Quarantine/Quarantine.module.js',
   'SBIS3.STATPROT.RuleConstructor': '/root/sbis3-eo-stat-prot/client/Админка/components/RuleConstructor/RuleConstructor.module.js',
   'SBIS3.STATPROT.Statistic': '/root/sbis3-eo-stat-prot/client/Админка/components/Statistic/Statistic.module.js',
   'SBIS3.STATPROT.UntypedErrors': '/root/sbis3-eo-stat-prot/client/Админка/components/UntypedErrors/UntypedErrors.module.js',
   'SBIS3.STATPROT.UpdateInterval': '/root/sbis3-eo-stat-prot/client/Админка/components/UpdateInterval/UpdateInterval.module.js',
   'SBIS3.Contragents.ChoiceOurCompany': '/root/sbis3-tender/tenderext-service/client/TenderExtUI/cap_modules/ChoiceOurCompany/ChoiceOurCompany.module.js',
   'SBIS3.Contragents.ChoiceOurCompanyLink': '/root/sbis3-tender/tenderext-service/client/TenderExtUI/cap_modules/ChoiceOurCompanyLink/ContragentChoice.module.js',
   'SBIS3.Contragents.ContragentCardPanel': '/root/sbis3-tender/tenderext-service/client/TenderExtUI/cap_modules/ContragentCardPanel/ContragentCardPanel.module.js',
   'SBIS3.Contragents.ContrDataCol': '/root/sbis3-tender/tenderext-service/client/TenderExtUI/cap_modules/ContrDataCol/ContrDataCol.module.js',
   'SBIS3.AddresseeChoice.FieldLink': '/root/sbis3-tender/tenderext-service/client/TenderExtUI/cap_modules/FieldLink/FieldLink.module.js',
   'SBIS3.Contragents.FunctionsCommon': '/root/sbis3-tender/tenderext-service/client/TenderExtUI/cap_modules/FunctionsCommon/FunctionsCommon.module.js',
   'SBIS3.Employee.ListEmployees': '/usermngt/personal-office/client/Личный аккаунт/Fixes/ListEmployees/ListEmployees-fix.module.js',
   'SBIS3.PT.OperationUnload': '/root/sbis3-tender/tenderext-service/client/TenderExtUI/cap_modules/OperationUnload/OperationUnload.module.js',
   'SBIS3.Contragents.OurCardCommonFunctions': '/usermngt/personal-office/client/Личный аккаунт/Fixes/OurCardCommonFunctions-fix.module.js',
   'SBIS3.Contragents.OurOrganizationChoice': '/usermngt/personal-office/client/Личный аккаунт/Fixes/OurOrganizationChoice-fix.module.js',
   'SBIS3.Contragents.Utils.OurOrgPublish': '/root/sbis3-tender/tenderext-service/client/TenderExtUI/cap_modules/OurOrgPublish/OurOrgPublish.module.js',
   'SBIS3.Employee.StaffChoice': '/usermngt/personal-office/client/Личный аккаунт/Fixes/StaffChoice-fix.module.js',
   'SBIS3.Employee.StaffChoiceHandlers': '/usermngt/personal-office/client/Личный аккаунт/Fixes/StaffChoiceHandlers-fix.module.js',
   'SBIS3.Staff.Choice.List': '/usermngt/personal-office/client/Личный аккаунт/Fixes/Choice/StaffChoiceList-fix.module.js',
   'SBIS3.TEST.TEST': '/sbis/core/test/tests/test-sbis-js/TestModule/test.module.js',
   'EmailControls': '/sbis/middleware/client/EmailControls/EmailControls.module.js',
   'SBIS3.EMAIL.EmailFooterEditInPlace': '/sbis/middleware/client/EmailControls/EmailFooterEditInPlace/EmailFooterEditInPlace.module.js',
   'SBIS3.Sitemap.DataSourceManagement': '/sbis/middleware/client/Sitemap/DataSourceManagement/DataSourceManagement.module.js',
   'SBIS3.Sitemap.DataSourceEditDialog': '/sbis/middleware/client/Sitemap/DataSourceManagement/resources/DataSourceEditDialog/DataSourceEditDialog.module.js',
   'SBIS3.Sitemap.Index': '/sbis/middleware/client/Sitemap/Index/Index.module.js',
   'SBIS3.Sitemap.DataSourceSelector': '/sbis/middleware/client/Sitemap/SiteManagement/resources/SiteDataSourceEditDialog/resources/DataSourceSelector/DataSourceSelector.module.js',
   'SBIS3.Sitemap.SiteDataSourceEditDialog': '/sbis/middleware/client/Sitemap/SiteManagement/resources/SiteDataSourceEditDialog/SiteDataSourceEditDialog.module.js',
   'SBIS3.Sitemap.SiteEditDialog': '/sbis/middleware/client/Sitemap/SiteManagement/resources/SiteEditDialog/SiteEditDialog.module.js',
   'SBIS3.Sitemap.SiteManagement': '/sbis/middleware/client/Sitemap/SiteManagement/SiteManagement.module.js',
   'SBIS3.Sitemap.CloudConfig': '/sbis/middleware/client/Sitemap/SitemapCloudConfig/SitemapCloudConfig.module.js',
   'SBIS3.Sitemap.View': '/sbis/middleware/client/Sitemap/View/View.module.js',
   'workflow': '/sbis/middleware/client/workflow-coordinator/workflow.module.js',
   'WAF': '/security/security/sbis-waf/client/sbis-waf/WAF.module.js',
   'SBIS3.SBIS.Breadcrumbs': '/sites/sbisru/client/common_sbis.ru/components/Breadcrumbs/Breadcrumbs.module.js',
   'SBIS3.SBIS.ClientsSlider': '/sites/sbisru/client/common_sbis.ru/components/ClientsSlider/ClientsSlider.module.js',
   'SBIS3.SBIS.Dialog': '/sites/sbisru/client/common_sbis.ru/components/Dialog/Dialog.module.js',
   'SBIS3.SBIS.DropDownObserver': '/sites/sbisru/client/common_sbis.ru/components/DropDownObserver/DropDownObserver.module.js',
   'SBIS3.SBIS.DropDownPanel': '/sites/sbisru/client/common_sbis.ru/components/DropDownPanel/DropDownPanel.module.js',
   'SBIS3.SBIS.DropDownPanelMenu': '/sites/sbisru/client/common_sbis.ru/components/DropDownPanelMenu/DropDownPanelMenu.module.js',
   'SBIS3.SBIS.Footer': '/sites/sbisru/client/common_sbis.ru/components/Footer/Footer.module.js',
   'SBIS3.SBIS.ContentImageList': '/sites/sbisru/client/common_sbis.ru/components/ContentImageList/ContentImageList.module.js',
   'SBIS3.SBIS.FooterNew': '/sites/sbisru/client/common_sbis.ru/components/FooterNew/FooterNew.module.js',
   'SBIS3.SBIS.GoodsList': '/sites/sbisru/client/common_sbis.ru/components/GoodsList/GoodsList.module.js',
   'SBIS3.SBIS.Header': '/sites/sbisru/client/common_sbis.ru/components/Header/Header.module.js',
   'SBIS3.SBIS.Logos': '/sites/sbisru/client/common_sbis.ru/components/Logos/Logos.module.js',
   'SBIS3.SBIS.Masonry': '/sites/sbisru/client/common_sbis.ru/components/Masonry/Masonry.module.js',
   'SBIS3.SBIS.MasterPageBase': '/sites/sbisru/client/common_sbis.ru/components/MasterPageBase/MasterPageBase.module.js',
   'SBIS3.SBIS.MainBanner': '/sites/sbisru/client/common_sbis.ru/components/MainBanner/MainBanner.module.js',
   'SBIS3.SBIS.Menu': '/sites/sbisru/client/common_sbis.ru/components/Menu/Menu.module.js',
   'SBIS3.SBIS.MiddleFixing': '/sites/sbisru/client/common_sbis.ru/components/MiddleFixing/MiddleFixing.module.js',
   'SBIS3.SBIS.MobileAppSection': '/sites/sbisru/client/common_sbis.ru/components/MobileAppSection/MobileAppSection.module.js',
   'SBIS3.SBIS.Overlay': '/sites/sbisru/client/common_sbis.ru/components/Overlay/Overlay.module.js',
   'SBIS3.SBIS.PageStorage': '/sites/sbisru/client/common_sbis.ru/components/PageStorage/PageStorage.module.js',
   'SBIS3.SBIS.RegionChooser': '/sites/sbisru/client/common_sbis.ru/components/RegionChooser/RegionChooser.module.js',
   'SBIS3.SBIS.ChooserPanel': '/sites/sbisru/client/common_sbis.ru/components/RegionChooser/resources/ChooserPanel/ChooserPanel.module.js',
   'SBIS3.SBIS.RegionManager': '/sites/sbisru/client/common_sbis.ru/components/RegionManager/RegionManager.module.js',
   'SBIS3.SBIS.RequestDialog': '/sites/sbisru/client/common_sbis.ru/components/RequestDialog/RequestDialog.module.js',
   'SBIS3.SBIS.RequestDropDown': '/sites/sbisru/client/common_sbis.ru/components/RequestDropDown/RequestDropDown.module.js',
   'SBIS3.SBIS.RequestManager': '/sites/sbisru/client/common_sbis.ru/components/RequestManager/RequestManager.module.js',
   'SBIS3.SBIS.ScrollContainer': '/sites/sbisru/client/common_sbis.ru/components/ScrollContainer/ScrollContainer.module.js',
   'SBIS3.SBIS.SearchForm.SearchSelector': '/sites/sbisru/client/common_sbis.ru/components/SearchForm/resources/SearchSelector/SearchSelector.module.js',
   'SBIS3.SBIS.SectionSlider': '/sites/sbisru/client/common_sbis.ru/components/SectionSlider/SectionSlider.module.js',
   'SBIS3.SBIS.SelectorDialogBase': '/sites/sbisru/client/common_sbis.ru/components/SelectorDialogBase/SelectorDialogBase.module.js',
   'SBIS3.SBIS.SearchForm': '/sites/sbisru/client/common_sbis.ru/components/SearchForm/SearchForm.module.js',
   'SBIS3.SBIS.SEO': '/sites/sbisru/client/common_sbis.ru/components/SEO/SEO.module.js',
   'SBIS3.SBIS.SubMenu': '/sites/sbisru/client/common_sbis.ru/components/SubMenu/SubMenu.module.js',
   'SBIS3.SBIS.UCRequestDialog': '/sites/sbisru/client/common_sbis.ru/components/UCRequestDialog/UCRequestDialog.module.js',
   'SBIS3.SBIS.VerticalTabs': '/sites/sbisru/client/common_sbis.ru/components/VerticalTabs/VerticalTabs.module.js',
   'SBIS3.VideoLink': '/sites/sbisru/client/common_sbis.ru/components/VideoLink/VideoLink.module.js',
   'SBIS3.VideoLinkWindow': '/sites/sbisru/client/common_sbis.ru/components/VideoLink/VideoLinkWindow/VideoLinkWindow.module.js',
   'SBIS3.SBIS.About': '/sites/sbisru/client/sbis.ru/components/About/About.module.js',
   'SBIS3.SBIS.AboutDev': '/sites/sbisru/client/sbis.ru/components/About/AboutDev/AboutDev.module.js',
   'SBIS3.SBIS.AboutDevMasterPage': '/sites/sbisru/client/sbis.ru/components/About/AboutDev/AboutDevMasterPage.module.js',
   'SBIS3.AboutGallery': '/sites/sbisru/client/sbis.ru/components/About/AboutGallery/AboutGallery.module.js',
   'SBIS3.MarkersSliderImages': '/sites/sbisru/client/sbis.ru/components/About/MarkersSliderImages/MarkersSliderImages.module.js',
   'SBIS3.SBIS.SketchGalleryPopup': '/sites/sbisru/client/sbis.ru/components/About/SketchGallery/SketchGalleryPopup/SketchGalleryPopup.module.js',
   'SBIS3.SBIS.SketchGallery': '/sites/sbisru/client/sbis.ru/components/About/SketchGallery/SketchGallery.module.js',
   'SBIS3.SBIS.AllServices': '/sites/sbisru/client/sbis.ru/components/AllServices/AllServices.module.js',
   'SBIS3.SBIS.API': '/sites/sbisru/client/sbis.ru/components/API/API.module.js',
   'SBIS3.SBIS.BusinessNetwork': '/sites/sbisru/client/sbis.ru/components/BusinessNetwork/BusinessNetwork.module.js',
   'SBIS3.SBIS.ApplicationPage': '/sites/sbisru/client/sbis.ru/components/BusinessProcesses/resources/solution/ApplicationPage/ApplicationPage.module.js',
   'SBIS3.SBIS.BusinessProcesses': '/sites/sbisru/client/sbis.ru/components/BusinessProcesses/BusinessProcesses.module.js',
   'SBIS3.SBIS.Catalog': '/sites/sbisru/client/sbis.ru/components/Catalog/Catalog.module.js',
   'SBIS3.SBIS.CatalogAutoTesting': '/sites/sbisru/client/sbis.ru/components/Catalog/CatalogAutoTesting/CatalogAutoTesting.module.js',
   'SBIS3.SBIS.CatalogCartStorage': '/sites/sbisru/client/sbis.ru/components/Catalog/CatalogCart/CatalogCartStorage.module.js',
   'SBIS3.SBIS.CatalogCart': '/sites/sbisru/client/sbis.ru/components/Catalog/CatalogCart/CatalogCart.module.js',
   'SBIS3.SBIS.CatalogItem': '/sites/sbisru/client/sbis.ru/components/Catalog/CatalogItem/CatalogItem.module.js',
   'SBIS3.SBIS.CatalogNomenclature': '/sites/sbisru/client/sbis.ru/components/Catalog/CatalogCart/CatalogNomenclature.module.js',
   'SBIS3.SBIS.CatalogListCatalogues': '/sites/sbisru/client/sbis.ru/components/Catalog/CatalogListCatalogues/CatalogListCatalogues.module.js',
   'SBIS3.SBIS.CatalogListItemsButton': '/sites/sbisru/client/sbis.ru/components/Catalog/CatalogListItems/resources/CatalogListItemsButton/CatalogListItemsButton.module.js',
   'SBIS3.SBIS.CatalogListItemsKit': '/sites/sbisru/client/sbis.ru/components/Catalog/CatalogListItemsKit/CatalogListItemsKit.module.js',
   'SBIS3.SBIS.CatalogMasterPage': '/sites/sbisru/client/sbis.ru/components/Catalog/CatalogMasterPage/CatalogMasterPage.module.js',
   'SBIS3.SBIS.CatalogListItems': '/sites/sbisru/client/sbis.ru/components/Catalog/CatalogListItems/CatalogListItems.module.js',
   'SBIS3.SBIS.ContragentMasterPage': '/sites/sbisru/client/sbis.ru/components/Contragents/Contragents/ContragentMasterPage.module.js',
   'SBIS3.SBIS.Contragents.helpers': '/sites/sbisru/client/sbis.ru/components/Contragents/Contragents/resources/helpers/helpers.module.js',
   'SBIS3.SBIS.ContragentsCommon': '/sites/sbisru/client/sbis.ru/components/Contragents/ContragentsCommon/ContragentsCommon.module.js',
   'SBIS3.SBIS.ContragentsCatList': '/sites/sbisru/client/sbis.ru/components/Contragents/ContragentsCatList/ContragentsCatList.module.js',
   'SBIS3.SBIS.ContragentsList': '/sites/sbisru/client/sbis.ru/components/Contragents/ContragentsList/ContragentsList.module.js',
   'SBIS3.SBIS.ContragentsListModel': '/sites/sbisru/client/sbis.ru/components/Contragents/ContragentsList/ContragentsListModel.module.js',
   'SBIS3.SBIS.ContragentsFullFilter.CategoryDialog': '/sites/sbisru/client/sbis.ru/components/Contragents/ContragentsList/resources/ContragentsFullFilter/resources/CategoryDialog/CategoryDialog.module.js',
   'SBIS3.SBIS.ContragentsFullFilter.RegionDialog': '/sites/sbisru/client/sbis.ru/components/Contragents/ContragentsList/resources/ContragentsFullFilter/resources/RegionDialog/RegionDialog.module.js',
   'SBIS3.SBIS.Contragents': '/sites/sbisru/client/sbis.ru/components/Contragents/Contragents/Contragents.module.js',
   'SBIS3.SBIS.ContragentsFullFilter': '/sites/sbisru/client/sbis.ru/components/Contragents/ContragentsList/resources/ContragentsFullFilter/ContragentsFullFilter.module.js',
   'SBIS3.SBIS.ContragentsMain': '/sites/sbisru/client/sbis.ru/components/Contragents/ContragentsMain/ContragentsMain.module.js',
   'SBIS3.SBIS.ContragentsMainModel': '/sites/sbisru/client/sbis.ru/components/Contragents/ContragentsMain/ContragentsMainModel.module.js',
   'SBIS3.SBIS.ContragentsOwnersList': '/sites/sbisru/client/sbis.ru/components/Contragents/ContragentsOwnersList/ContragentsOwnersList.module.js',
   'SBIS3.SBIS.ContragentsOwnersListModel': '/sites/sbisru/client/sbis.ru/components/Contragents/ContragentsOwnersList/ContragentsOwnersListModel.module.js',
   'SBIS3.SBIS.ContragentsFastFilter': '/sites/sbisru/client/sbis.ru/components/Contragents/ContragentsMain/resources/ContragentsFastFilter/ContragentsFastFilter.module.js',
   'SBIS3.SBIS.ContragentsRegionList': '/sites/sbisru/client/sbis.ru/components/Contragents/ContragentsRegionList/ContragentsRegionList.module.js',
   'SBIS3.SBIS.ContragentsServicePageArea': '/sites/sbisru/client/sbis.ru/components/Contragents/ContragentsServicePageArea/ContragentsServicePageArea.module.js',
   'SBIS3.SBIS.ContragentsRegionListModel': '/sites/sbisru/client/sbis.ru/components/Contragents/ContragentsRegionList/ContragentsRegionListModel.module.js',
   'SBIS3.SBIS.ContragentsTasksTemplate': '/sites/sbisru/client/sbis.ru/components/Contragents/ContragentsTasksTemplate/ContragentsTasksTemplate.module.js',
   'SBIS3.SBIS.CryptoPro': '/sites/sbisru/client/sbis.ru/components/CryptoPro/CryptoPro.module.js',
   'SBIS3.SBIS.CryptoProUC': '/sites/sbisru/client/sbis.ru/components/CryptoProUC/CryptoProUC.module.js',
   'SBIS3.SBIS.Delivery': '/sites/sbisru/client/sbis.ru/components/Delivery/Delivery.module.js',
   'SBIS3.SBIS.DownloadNew': '/sites/sbisru/client/sbis.ru/components/DownloadNew/DownloadNew.module.js',
   'SBIS3.SBIS.DownloadNewDoc': '/sites/sbisru/client/sbis.ru/components/DownloadNew/DownloadNewDoc/DownloadNewDoc.module.js',
   'SBIS3.SBIS.DownloadNewMasterPage': '/sites/sbisru/client/sbis.ru/components/DownloadNew/DownloadNewMasterPage.module.js',
   'SBIS3.SBIS.EDI': '/sites/sbisru/client/sbis.ru/components/EDI/EDI.module.js',
   'SBIS3.SBIS.EDO': '/sites/sbisru/client/sbis.ru/components/EDO/EDO.module.js',
   'SBIS3.SBIS.EDO.BankSolution': '/sites/sbisru/client/sbis.ru/components/EDO/resources/components/BankSolution/BankSolution.module.js',
   'SBIS3.SBIS.EDO.FactoringSolution': '/sites/sbisru/client/sbis.ru/components/EDO/resources/components/FactoringSolution/FactoringSolution.module.js',
   'SBIS3.SBIS.EDO.LogisticSolution': '/sites/sbisru/client/sbis.ru/components/EDO/resources/components/LogisticSolution/LogisticSolution.module.js',
   'SBIS3.SBIS.EDO.PharmaSolution': '/sites/sbisru/client/sbis.ru/components/EDO/resources/components/PharmaSolution/PharmaSolution.module.js',
   'SBIS3.SBIS.EDO.ProductionSolution': '/sites/sbisru/client/sbis.ru/components/EDO/resources/components/ProductionSolution/ProductionSolution.module.js',
   'SBIS3.SBIS.EDO.SolutionTemplate': '/sites/sbisru/client/sbis.ru/components/EDO/resources/components/SolutionTemplate/SolutionTemplate.module.js',
   'SBIS3.SBIS.EDO.RetailCateringSolution': '/sites/sbisru/client/sbis.ru/components/EDO/resources/components/RetailCateringSolution/RetailCateringSolution.module.js',
   'SBIS3.SBIS.EDO.SolutionTitlePart': '/sites/sbisru/client/sbis.ru/components/EDO/resources/components/SolutionTemplate/SolutionTitlePart/SolutionTitlePart.module.js',
   'SBIS3.SBIS.EDO.TelecomSolution': '/sites/sbisru/client/sbis.ru/components/EDO/resources/components/TelecomSolution/TelecomSolution.module.js',
   'SBIS3.SBIS.EDO.PagesTemplate': '/sites/sbisru/client/sbis.ru/components/EDO/resources/pagesComments/PagesTemplate/PagesTemplate.module.js',
   'SBIS3.LogosTemplate': '/sites/sbisru/client/sbis.ru/components/EDO/resources/LogosTemplate/LogosTemplate.module.js',
   'SBIS3.SBIS.EDO.EnergoSolution': '/sites/sbisru/client/sbis.ru/components/EDO/resources/components/EnergoSolution/EnergoSolution.module.js',
   'SBIS3.SBIS.EDO.PagesTitlePart': '/sites/sbisru/client/sbis.ru/components/EDO/resources/pagesComments/PagesTemplate/PagesTitlePart/PagesTitlePart.module.js',
   'SBIS3.SBIS.EDO.UrsaPage': '/sites/sbisru/client/sbis.ru/components/EDO/resources/pagesComments/ProductionPages/Ursa/UrsaPage.module.js',
   'SBIS3.SBIS.EDO.AmwayPage': '/sites/sbisru/client/sbis.ru/components/EDO/resources/pagesComments/RetailCatering/Amway/AmwayPage.module.js',
   'SBIS3.SliderTemplate': '/sites/sbisru/client/sbis.ru/components/EDO/resources/SliderTemplate/SliderTemplate.module.js',
   'SBIS3.SBIS.SliderTemplateOther': '/sites/sbisru/client/sbis.ru/components/EDO/resources/SliderTemplateOther/SliderTemplateOther.module.js',
   'SBIS3.SBIS.CertificationCenterEdo': '/sites/sbisru/client/sbis.ru/components/EDO/resources/solutions/CertificationCenter/CertificationCenterEdo.module.js',
   'SBIS3.SBIS.EmailEdo': '/sites/sbisru/client/sbis.ru/components/EDO/resources/solutions/Email/EmailEdo.module.js',
   'SBIS3.SBIS.SiteEdo': '/sites/sbisru/client/sbis.ru/components/EDO/resources/solutions/Site/SiteEdo.module.js',
   'SBIS3.SBIS.EReport': '/sites/sbisru/client/sbis.ru/components/EReport/EReport.module.js',
   'SBIS3.SBIS.Special': '/sites/sbisru/client/sbis.ru/components/EReport/PromoutPages/Special/Special.module.js',
   'SBIS3.SBIS.Perehodi': '/sites/sbisru/client/sbis.ru/components/EReport/PromoutPages/Perehodi/Perehodi.module.js',
   'SBIS3.SBIS.LinkImage': '/sites/sbisru/client/sbis.ru/components/EReport/resources/LinkImage/LinkImage.module.js',
   'SBIS3.SBIS.HowToChoose': '/sites/sbisru/client/sbis.ru/components/HowToChoose/HowToChoose.module.js',
   'SBIS3.SBIS.HowToChooseMasterPage': '/sites/sbisru/client/sbis.ru/components/HowToChoose/HowToChooseMasterPage/HowToChooseMasterPage.module.js',
   'SBIS3.SBIS.Index': '/sites/sbisru/client/sbis.ru/components/Index/Index.module.js',
   'SBIS3.SBIS.IndexMasterPage': '/sites/sbisru/client/sbis.ru/components/Index/IndexMasterPage.module.js',
   'SBIS3.SBIS.LandingMasterPage': '/sites/sbisru/client/sbis.ru/components/Index/LandingMasterPage.module.js',
   'SBIS3.SBIS.Issuer': '/sites/sbisru/client/sbis.ru/components/Issuer/Issuer.module.js',
   'SBIS3.SBIS.IssuerMasterPage': '/sites/sbisru/client/sbis.ru/components/Issuer/IssuerMasterPage.module.js',
   'SBIS3.SBIS.License': '/sites/sbisru/client/sbis.ru/components/License/License.module.js',
   'SBIS3.SBIS.License.ImageDialog': '/sites/sbisru/client/sbis.ru/components/License/resources/ImageDialog/ImageDialog.module.js',
   'SBIS3.SBIS.OFD.54FZ': '/sites/sbisru/client/sbis.ru/components/OFD/54FZ/54FZ.module.js',
   'SBIS3.SBIS.OFD.54FZEnvd': '/sites/sbisru/client/sbis.ru/components/OFD/54FZEnvd/54FZEnvd.module.js',
   'SBIS3.SBIS.OFD.About': '/sites/sbisru/client/sbis.ru/components/OFD/About/About.module.js',
   'SBIS3.SBIS.CompanyOfficesDropDown': '/sites/sbisru/client/sbis.ru/components/OFD/CompanyOffices/CompanyOfficesDropDown/CompanyOfficesDropDown.module.js',
   'SBIS3.SBIS.OFD.CompanyOffices': '/sites/sbisru/client/sbis.ru/components/OFD/CompanyOffices/CompanyOffices.module.js',
   'SBIS3.SBIS.OFD.CompanyOfficesModel': '/sites/sbisru/client/sbis.ru/components/OFD/CompanyOffices/CompanyOfficesModel.module.js',
   'SBIS3.SBIS.OFD.CompanyOfficesMasterPage': '/sites/sbisru/client/sbis.ru/components/OFD/CompanyOffices/CompanyOfficesMasterPage.module.js',
   'SBIS3.SBIS.OFD.FiscalStorage': '/sites/sbisru/client/sbis.ru/components/OFD/FiscalStorage/FiscalStorage.module.js',
   'SBIS3.SBIS.OFD.KKTWizard': '/sites/sbisru/client/sbis.ru/components/OFD/KKTWizard/KKTWizard.module.js',
   'SBIS3.SBIS.OFD.WizardFooter': '/sites/sbisru/client/sbis.ru/components/OFD/KKTWizard/resources/WizardFooter/WizardFooter.module.js',
   'SBIS3.SBIS.OFD.WizardHeader': '/sites/sbisru/client/sbis.ru/components/OFD/KKTWizard/resources/WizardHeader/WizardHeader.module.js',
   'SBIS3.SBIS.OFD.WizardStep1': '/sites/sbisru/client/sbis.ru/components/OFD/KKTWizard/resources/WizardStep1/WizardStep1.module.js',
   'SBIS3.SBIS.OFD.WizardStep2': '/sites/sbisru/client/sbis.ru/components/OFD/KKTWizard/resources/WizardStep2/WizardStep2.module.js',
   'SBIS3.SBIS.OFD.WizardStep3': '/sites/sbisru/client/sbis.ru/components/OFD/KKTWizard/resources/WizardStep3/WizardStep3.module.js',
   'SBIS3.SBIS.OFD.WizardStep4': '/sites/sbisru/client/sbis.ru/components/OFD/KKTWizard/resources/WizardStep4/WizardStep4.module.js',
   'SBIS3.SBIS.OFD.WizardStep5': '/sites/sbisru/client/sbis.ru/components/OFD/KKTWizard/resources/WizardStep5/WizardStep5.module.js',
   'SBIS3.SBIS.Modernization': '/sites/sbisru/client/sbis.ru/components/OFD/Modernization/Modernization.module.js',
   'SBIS3.SBIS.OFD.OFDEnvd': '/sites/sbisru/client/sbis.ru/components/OFD/OFDEnvd/OFDEnvd.module.js',
   'SBIS3.SBIS.LogosOFD': '/sites/sbisru/client/sbis.ru/components/OFD/resources/LogosOFD/LogosOFD.module.js',
   'SBIS3.SBIS.OFD': '/sites/sbisru/client/sbis.ru/components/OFD/OFD.module.js',
   'SBIS3.SBIS.Offer': '/sites/sbisru/client/sbis.ru/components/Offer/Offer.module.js',
   'SBIS3.SBIS.Partneram': '/sites/sbisru/client/sbis.ru/components/Partneram/Partneram.module.js',
   'SBIS3.SBIS.CafeBar': '/sites/sbisru/client/sbis.ru/components/Presto/CafeBar/CafeBar.module.js',
   'SBIS3.SBIS.Canteen': '/sites/sbisru/client/sbis.ru/components/Presto/Canteen/Canteen.module.js',
   'SBIS3.SBIS.Policy': '/sites/sbisru/client/sbis.ru/components/Policy/Policy.module.js',
   'SBIS3.SBIS.PolicyOther': '/sites/sbisru/client/sbis.ru/components/PolicyOther/PolicyOther.module.js',
   'SBIS3.SBIS.Kitchen': '/sites/sbisru/client/sbis.ru/components/Presto/Kitchen/Kitchen.module.js',
   'SBIS3.SBIS.FastFood': '/sites/sbisru/client/sbis.ru/components/Presto/FastFood/FastFood.module.js',
   'SBIS3.SBIS.PrestoTooltip': '/sites/sbisru/client/sbis.ru/components/Presto/resources/PrestoTooltip/PrestoTooltip.module.js',
   'SBIS3.SBIS.Presto': '/sites/sbisru/client/sbis.ru/components/Presto/Presto.module.js',
   'SBIS3.SBIS.ServiceTables': '/sites/sbisru/client/sbis.ru/components/Presto/ServiceTables/ServiceTables.module.js',
   'SBIS3.SBIS.PricesTariffsMasterPage': '/sites/sbisru/client/sbis.ru/components/PricesTariffs/PricesTariffsMasterPage.module.js',
   'SBIS3.SBIS.RestaurantChain': '/sites/sbisru/client/sbis.ru/components/Presto/RestaurantChain/RestaurantChain.module.js',
   'SBIS3.SBIS.PricesTariffs': '/sites/sbisru/client/sbis.ru/components/PricesTariffs/PricesTariffs.module.js',
   'SBIS3.SBIS.Reglament': '/sites/sbisru/client/sbis.ru/components/Reglament/Reglament.module.js',
   'SBIS3.SBIS.AutonomousOfficeHowToChoose': '/sites/sbisru/client/sbis.ru/components/SalesPoint/AutonomousOfficeHowToChoose/AutonomousOfficeHowToChoose.module.js',
   'SBIS3.SBIS.CashOfficesForHairdressers': '/sites/sbisru/client/sbis.ru/components/SalesPoint/CashOfficesForHairdressers/CashOfficesForHairdressers.module.js',
   'SBIS3.SBIS.CashRegisterComputerHowToChoose': '/sites/sbisru/client/sbis.ru/components/SalesPoint/CashRegisterComputerHowToChoose/CashRegisterComputerHowToChoose.module.js',
   'SBIS3.SBIS.CheckPrinterHowToChoose': '/sites/sbisru/client/sbis.ru/components/SalesPoint/CheckPrinterHowToChoose/CheckPrinterHowToChoose.module.js',
   'SBIS3.SBIS.CustomerDisplayHowToChoose': '/sites/sbisru/client/sbis.ru/components/SalesPoint/CustomerDisplayHowToChoose/CustomerDisplayHowToChoose.module.js',
   'SBIS3.SBIS.DetectorsHowToChoose': '/sites/sbisru/client/sbis.ru/components/SalesPoint/DetectorsHowToChoose/DetectorsHowToChoose.module.js',
   'SBIS3.SBIS.EquipmentSetRegistry': '/sites/sbisru/client/sbis.ru/components/SalesPoint/EquipmentSetRegistry/EquipmentSetRegistry.module.js',
   'SBIS3.SBIS.ElectronicScalesHowToChoose': '/sites/sbisru/client/sbis.ru/components/SalesPoint/ElectronicScalesHowToChoose/ElectronicScalesHowToChoose.module.js',
   'SBIS3.SBIS.EquipmentSetCart': '/sites/sbisru/client/sbis.ru/components/SalesPoint/EquipmentSetRegistry/resources/EquipmentSetCart/EquipmentSetCart.module.js',
   'SBIS3.SBIS.FiscalHowToChoose': '/sites/sbisru/client/sbis.ru/components/SalesPoint/FiscalHowToChoose/FiscalHowToChoose.module.js',
   'SBIS3.SBIS.LabelPrintersHowToChoose': '/sites/sbisru/client/sbis.ru/components/SalesPoint/LabelPrintersHowToChoose/LabelPrintersHowToChoose.module.js',
   'SBIS3.SBIS.MoneyBoxHowToChoose': '/sites/sbisru/client/sbis.ru/components/SalesPoint/MoneyBoxHowToChoose/MoneyBoxHowToChoose.module.js',
   'SBIS3.SBIS.OnlineOfficesHowToChoose': '/sites/sbisru/client/sbis.ru/components/SalesPoint/OnlineOfficesHowToChoose/OnlineOfficesHowToChoose.module.js',
   'SBIS3.SBIS.PosEquipmentHowToChoose': '/sites/sbisru/client/sbis.ru/components/SalesPoint/PosEquipmentHowToChoose/PosEquipmentHowToChoose.module.js',
   'SBIS3.SBIS.SalesPoint': '/sites/sbisru/client/sbis.ru/components/SalesPoint/SalesPoint.module.js',
   'SBIS3.SBIS.ScannersHowToChoose': '/sites/sbisru/client/sbis.ru/components/SalesPoint/ScannersHowToChoose/ScannersHowToChoose.module.js',
   'SBIS3.SBIS.SalesPoints.MapWindow': '/sites/sbisru/client/sbis.ru/components/SbisContacts/SalesPoints/MapWindow/MapWindow.module.js',
   'SBIS3.SBIS.SalesPointTooltip': '/sites/sbisru/client/sbis.ru/components/SalesPoint/resources/SalesPointTooltip/SalesPointTooltip.module.js',
   'SBIS3.SBIS.SalesPoints': '/sites/sbisru/client/sbis.ru/components/SbisContacts/SalesPoints/SalesPoints.module.js',
   'SBIS3.SBIS.SalesPointsMasterPage': '/sites/sbisru/client/sbis.ru/components/SbisContacts/SalesPoints/SalesPointsMasterPage.module.js',
   'SBIS3.SalesPointsMobile': '/sites/sbisru/client/sbis.ru/components/SbisContacts/SalesPoints/SalesPointsMobile/SalesPointsMobile.module.js',
   'SBIS3.SBIS.SalesPointsModel': '/sites/sbisru/client/sbis.ru/components/SbisContacts/SalesPoints/SalesPointsModel.module.js',
   'SBIS3.SBIS.Support': '/sites/sbisru/client/sbis.ru/components/SbisContacts/Support/Support.module.js',
   'SBIS3.SBIS.SupportForBusiness': '/sites/sbisru/client/sbis.ru/components/SbisContacts/Support/SupportForBusiness/SupportForBusiness.module.js',
   'SBIS3.SBIS.SupportLinks': '/sites/sbisru/client/sbis.ru/components/SbisContacts/Support/SupportLinks/SupportLinks.module.js',
   'SBIS3.SBIS.SupportMasterPage': '/sites/sbisru/client/sbis.ru/components/SbisContacts/Support/SupportMasterPage.module.js',
   'SBIS3.SBIS.SupportMenu': '/sites/sbisru/client/sbis.ru/components/SbisContacts/Support/SupportMenu/SupportMenu.module.js',
   'SBIS3.SBIS.SupportVideoElement': '/sites/sbisru/client/sbis.ru/components/SbisContacts/Support/VideoInstructions/resources/SupportVideoElement/SupportVideoElement.module.js',
   'SBIS3.SBIS.SupportQuestions': '/sites/sbisru/client/sbis.ru/components/SbisContacts/Support/SupportQuestions/SupportQuestions.module.js',
   'SBIS3.VideoInstructionsMobile': '/sites/sbisru/client/sbis.ru/components/SbisContacts/Support/VideoInstructionsMobile/VideoInstructionsMobile.module.js',
   'SBIS3.SBIS.VideoInstructions': '/sites/sbisru/client/sbis.ru/components/SbisContacts/Support/VideoInstructions/VideoInstructions.module.js',
   'SBIS3.SBIS.Tariffs': '/sites/sbisru/client/sbis.ru/components/SbisContacts/Tariffs/Tariffs.module.js',
   'SBIS3.SBIS.ScrollHeaderControl': '/sites/sbisru/client/sbis.ru/components/ScrollHeaderControl/ScrollHeaderControl.module.js',
   'SBIS3.SBIS.TariffsInfo': '/sites/sbisru/client/sbis.ru/components/SbisContacts/TariffsInfo/TariffsInfo.module.js',
   'SBIS3.SBIS.servicePageArea.helper': '/sites/sbisru/client/sbis.ru/components/servicePageArea/resources/helper/helper.module.js',
   'SBIS3.SBIS.servicePageArea': '/sites/sbisru/client/sbis.ru/components/servicePageArea/servicePageArea.module.js',
   'SBIS3.SBIS.Staff': '/sites/sbisru/client/sbis.ru/components/Staff/Staff.module.js',
   'SBIS3.SBIS.TabDevices': '/sites/sbisru/client/sbis.ru/components/TabDevices/TabDevices.module.js',
   'SBIS3.SBIS.TabsTest': '/sites/sbisru/client/sbis.ru/components/TabsTest/TabsTest.module.js',
   'SBIS3.SBIS.TenderCard': '/sites/sbisru/client/sbis.ru/components/Tenders/TenderCard/TenderCard.module.js',
   'SBIS3.SBIS.TenderCardModel': '/sites/sbisru/client/sbis.ru/components/Tenders/TenderCard/TenderCardModel.module.js',
   'SBIS3.SBIS.Tenders.helpers': '/sites/sbisru/client/sbis.ru/components/Tenders/Tenders/resources/helpers/helpers.module.js',
   'SBIS3.SBIS.TenderMasterPage': '/sites/sbisru/client/sbis.ru/components/Tenders/Tenders/TenderMasterPage.module.js',
   'SBIS3.SBIS.Tenders': '/sites/sbisru/client/sbis.ru/components/Tenders/Tenders/Tenders.module.js',
   'SBIS3.SBIS.TendersCatList': '/sites/sbisru/client/sbis.ru/components/Tenders/TendersCatList/TendersCatList.module.js',
   'SBIS3.SBIS.TendersCatListModel': '/sites/sbisru/client/sbis.ru/components/Tenders/TendersCatList/TendersCatListModel.module.js',
   'SBIS3.SBIS.TendersFullFilter.CategoryDialog': '/sites/sbisru/client/sbis.ru/components/Tenders/TendersList/resources/TendersFullFilter/resources/CategoryDialog/CategoryDialog.module.js',
   'SBIS3.SBIS.TendersContractorList': '/sites/sbisru/client/sbis.ru/components/Tenders/TendersContractorList/TendersContractorList.module.js',
   'SBIS3.SBIS.TendersFullFilter.OrganizationDialog': '/sites/sbisru/client/sbis.ru/components/Tenders/TendersList/resources/TendersFullFilter/resources/OrganizationDialog/OrganizationDialog.module.js',
   'SBIS3.SBIS.TendersFullFilter.PlatformDialog': '/sites/sbisru/client/sbis.ru/components/Tenders/TendersList/resources/TendersFullFilter/resources/PlatformDialog/PlatformDialog.module.js',
   'SBIS3.SBIS.TendersFullFilter.RegionDialog': '/sites/sbisru/client/sbis.ru/components/Tenders/TendersList/resources/TendersFullFilter/resources/RegionDialog/RegionDialog.module.js',
   'SBIS3.SBIS.TendersFullFilter': '/sites/sbisru/client/sbis.ru/components/Tenders/TendersList/resources/TendersFullFilter/TendersFullFilter.module.js',
   'SBIS3.SBIS.TendersList': '/sites/sbisru/client/sbis.ru/components/Tenders/TendersList/TendersList.module.js',
   'SBIS3.SBIS.TendersListModel': '/sites/sbisru/client/sbis.ru/components/Tenders/TendersList/TendersListModel.module.js',
   'SBIS3.SBIS.LastTenders': '/sites/sbisru/client/sbis.ru/components/Tenders/TendersMain/resources/LastTenders/LastTenders.module.js',
   'SBIS3.SBIS.TendersFullFilter.PlatformDialogModel': '/sites/sbisru/client/sbis.ru/components/Tenders/TendersList/resources/TendersFullFilter/resources/PlatformDialog/PlatformDialogModel.module.js',
   'SBIS3.SBIS.SimpleSlider': '/sites/sbisru/client/sbis.ru/components/Tenders/TendersMain/resources/SimpleSlider/SimpleSlider.module.js',
   'SBIS3.SBIS.TendersFastFilter': '/sites/sbisru/client/sbis.ru/components/Tenders/TendersMain/resources/TendersFastFilter/TendersFastFilter.module.js',
   'SBIS3.SBIS.TendersMain': '/sites/sbisru/client/sbis.ru/components/Tenders/TendersMain/TendersMain.module.js',
   'SBIS3.SBIS.TendersMainModel': '/sites/sbisru/client/sbis.ru/components/Tenders/TendersMain/TendersMainModel.module.js',
   'SBIS3.SBIS.TendersOrgList': '/sites/sbisru/client/sbis.ru/components/Tenders/TendersOrgList/TendersOrgList.module.js',
   'SBIS3.SBIS.TendersReferral': '/sites/sbisru/client/sbis.ru/components/Tenders/TendersReferral/TendersReferral.module.js',
   'SBIS3.SBIS.TendersRegionList': '/sites/sbisru/client/sbis.ru/components/Tenders/TendersRegionList/TendersRegionList.module.js',
   'SBIS3.SBIS.TendersServicePageArea': '/sites/sbisru/client/sbis.ru/components/Tenders/TendersServicePageArea/TendersServicePageArea.module.js',
   'SBIS3.SBIS.VideoCommunications': '/sites/sbisru/client/sbis.ru/components/VideoCommunications/VideoCommunications.module.js',
   'SBIS3.SBIS.View': '/sites/sbisru/client/Theme/View/View.module.js',
   'SBIS3.SBIS.Wrapper': '/sites/sbisru/client/Theme/Wrapper/Wrapper.module.js',
   'SBIS3.SBIS.ContragentCardHeader': '/sites/sbisru/client/Контрагенты sbis.ru/components/ContragentCard/ContragentCardHeader/ContragentCardHeader.module.js',
   'SBIS3.SBIS.ContragentCardDataRequest': '/sites/sbisru/client/Контрагенты sbis.ru/components/ContragentCard/ContragentCardDataRequest/ContragentCardDataRequest.module.js',
   'SBIS3.Contragents.ContragentCardSbisView': '/sites/sbisru/client/Контрагенты sbis.ru/components/ContragentCard/ContragentCardSbisView/ContragentCardSbisView.module.js',
   'SBIS3.SBIS.ContragentCardUtils': '/sites/sbisru/client/Контрагенты sbis.ru/components/ContragentCard/ContragentCardUtils/ContragentCardUtils.module.js',
   'SBIS3.TENSOR.Footer': '/sites/tensor_ru/client/common_tensorru/Footer/Footer.module.js',
   'SBIS3.SBIS.ContragentsReferral': '/sites/sbisru/client/Контрагенты sbis.ru/components/ContragentsReferral/ContragentsReferral.module.js',
   'SBIS3.TENSOR.Header': '/sites/tensor_ru/client/common_tensorru/Header/Header.module.js',
   'SBIS3.TENSOR.HeaderDropDownMenu': '/sites/tensor_ru/client/common_tensorru/HeaderDropDownMenu/HeaderDropDownMenu.module.js',
   'SBIS3.TENSOR.MasterPageBase': '/sites/tensor_ru/client/common_tensorru/MasterPageBase/MasterPageBase.module.js',
   'SBIS3.TENSOR.Center': '/sites/tensor_ru/client/tensor.ru/components/CTO/Center/Center.module.js',
   'SBIS3.TENSOR.Contacts': '/sites/tensor_ru/client/tensor.ru/components/CTO/Contacts/Contacts.module.js',
   'SBIS3.TENSOR.ContactsMasterPage': '/sites/tensor_ru/client/tensor.ru/components/CTO/Contacts/ContactsMasterPage.module.js',
   'SBIS3.SBIS.ContactsModel': '/sites/tensor_ru/client/tensor.ru/components/CTO/Contacts/ContactsModel.module.js',
   'SBIS3.TENSOR.ContactsDropDown': '/sites/tensor_ru/client/tensor.ru/components/CTO/Contacts/templates/CompanyOfficesDropDown/ContactsDropDown.module.js',
   'SBIS3.TENSOR.MapWindow': '/sites/tensor_ru/client/tensor.ru/components/CTO/Contacts/templates/MapWindow/MapWindow.module.js',
   'SBIS3.TENSOR.Tariffs': '/sites/tensor_ru/client/tensor.ru/components/CTO/Tariffs/Tariffs.module.js',
   'SBIS3.TENSOR.TariffsMasterPage': '/sites/tensor_ru/client/tensor.ru/components/CTO/Tariffs/TariffsMasterPage.module.js',
   'SBIS3.TENSOR.PricesAutoTesting': '/sites/tensor_ru/client/tensor.ru/components/Prices/PricesAutoTesting/PricesAutoTesting.module.js',
   'SBIS3.TENSOR.EngineerRequest': '/sites/tensor_ru/client/tensor.ru/components/Requests/EngineerRequest/EngineerRequest.module.js',
   'SBIS3.TENSOR.Index': '/sites/tensor_ru/client/tensor.ru/components/Index/Index.module.js',
   'SBIS3.TENSOR.PriceManager': '/sites/tensor_ru/client/tensor.ru/components/Requests/PriceManager/PriceManager.module.js',
   'SBIS3.TENSOR.TradeRequest': '/sites/tensor_ru/client/tensor.ru/components/Requests/TradeRequest/TradeRequest.module.js',
   'SBIS3.TENSOR.SEO': '/sites/tensor_ru/client/tensor.ru/components/SEO/SEO.module.js',
   'SBIS3.TENSOR.UCRequest': '/sites/tensor_ru/client/tensor.ru/components/Requests/UCRequest/UCRequest.module.js',
   'SBIS3.TENSOR.UC.Center': '/sites/tensor_ru/client/tensor.ru/components/UC/Center/Center.module.js',
   'SBIS3.TENSOR.UC.Consulting': '/sites/tensor_ru/client/tensor.ru/components/UC/Consulting/Consulting.module.js',
   'SBIS3.TENSOR.UC.Contacts': '/sites/tensor_ru/client/tensor.ru/components/UC/Contacts/Contacts.module.js',
   'SBIS3.TENSOR.UC.ContactsMasterPage': '/sites/tensor_ru/client/tensor.ru/components/UC/Contacts/ContactsMasterPage.module.js',
   'SBIS3.TENSOR.UC.ContactsModel': '/sites/tensor_ru/client/tensor.ru/components/UC/Contacts/ContactsModel.module.js',
   'SBIS3.TENSOR.UC.License': '/sites/tensor_ru/client/tensor.ru/components/UC/License/License.module.js',
   'SBIS3.TENSOR.UC.Support': '/sites/tensor_ru/client/tensor.ru/components/UC/Support/Support.module.js',
   'SBIS3.TENSOR.UC.LicenseCP': '/sites/tensor_ru/client/tensor.ru/components/UC/LicenseCP/LicenseCP.module.js',
   'SBIS3.TENSOR.UC.SupportMasterPage': '/sites/tensor_ru/client/tensor.ru/components/UC/Support/SupportMasterPage.module.js',
   'SBIS3.TENSOR.UC.Tariffs': '/sites/tensor_ru/client/tensor.ru/components/UC/Tariffs/Tariffs.module.js',
   'SBIS3.TENSOR.UC.TariffsMasterPage': '/sites/tensor_ru/client/tensor.ru/components/UC/Tariffs/TariffsMasterPage.module.js',
   'SBIS3.TENSOR.UC.TradingPlatforms': '/sites/tensor_ru/client/tensor.ru/components/UC/TradingPlatforms/TradingPlatforms.module.js',
   'Tags': '/socnet/tags/client/Tags/Tags.module.js',
   'SBIS3.TENSOR.View': '/sites/tensor_ru/client/ThemeTensor/View/View.module.js',
   'SMSTransport': '/sms/sms-transport/client/SMSTransport/SMSTransport.module.js',
   'SBIS3.PrivateCertificates.AccessAndSigns': '/usermngt/personal-office/client/Личный аккаунт/components/AccessAndSigns/AccessAndSigns.module.js',
   'SBIS3.SBISDISK.DocsNavigationHandlers': '/usermngt/personal-office/client/Личный аккаунт/components/DocsNavigationHandlers/DocsNavigationHandlers.module.js',
   'SBIS3.PersonalOffice.MasterPage': '/usermngt/personal-office/client/Личный аккаунт/components/MasterPage/MasterPage.module.js',
   'SBIS3.PersonalOffice.Pages.MyProfilePage': 'personal-officeclient/Личный аккаунт/components/MyProfilePage/MyProfilePage.module.js',
   'SBIS3.PersonalOffice.OnlineBaseInnerPersonalOffice': '/usermngt/personal-office/client/Личный аккаунт/components/PersonalOfficeMasterPage/OnlineBaseInnerPersonalOffice.module.js',
   'SBIS3.StaffProfile.ProfileAccess': '/usermngt/personal-office/client/Личный аккаунт/components/ProfileAccess/ProfileAccess.module.js',
   'SBIS3.QuickAccessToolbar.ButtonQuickRegulations': '/usermngt/personal-office/client/Личный аккаунт/components/QuickAccess/Regulations.module.js',
   'SBIS3.QuickAccessToolbar.Toolbar': '/usermngt/personal-office/client/Личный аккаунт/components/QuickAccess/Toolbar.module.js',
   'SBIS3.EDO.CD.SDPagePersonalAccount': '/usermngt/personal-office/client/Личный аккаунт/components/SDPagePersonalAccount/SDPagePersonalAccount.module.js',
   'SBIS3.PersonalOffice.StartPage': '/usermngt/personal-office/client/Личный аккаунт/components/StartPage/StartPage.module.js',
   'SBIS3.Analytics.BusinessValuation': '/usermngt/personal-office/client/Личный аккаунт/Fixes/BusinessValuation-fix.module.js',
   'SBIS3.BUH.BANK.ContragentRSList': '/usermngt/personal-office/client/Личный аккаунт/Fixes/ContragentRSList-fix.module.js',
   'SBIS3.Employee.CoreEmployees': '/usermngt/personal-office/client/Личный аккаунт/Fixes/CoreEmployees-fix.module.js',
   'SBIS3.DEAL.DocIndexList': '/usermngt/personal-office/client/Личный аккаунт/Fixes/DocIndexList.module.js',
   'SBIS3.EDO.EDOFilter': '/usermngt/personal-office/client/Личный аккаунт/Fixes/EDOFilter-fix.module.js',
   'SBIS3.Analytics.Credit': '/usermngt/personal-office/client/Личный аккаунт/Fixes/Credit-fix.module.js',
   'SBIS3.NP.DirectionOfCompletion': '/usermngt/personal-office/client/Личный аккаунт/Fixes/DirectionOfCompletion-fix.module.js',
   'SBIS3.EDO.EdoHandlers': '/usermngt/personal-office/client/Личный аккаунт/Fixes/EDOHandlers-fix.module.js',
   'SBIS3.EDO.EdoReestrColumnRenders': '/usermngt/personal-office/client/Личный аккаунт/Fixes/EdoReestrColumnRenders-fix.module.js',
   'SBIS3.BUH.DocPanel': '/usermngt/personal-office/client/Личный аккаунт/Fixes/DocPanel-fix.module.js',
   'SBIS3.EDO.EdoReestrHandlers': '/usermngt/personal-office/client/Личный аккаунт/Fixes/EdoReestrHandlers-fix.module.js',
   'SBIS3.Employee.Choice': '/usermngt/personal-office/client/Личный аккаунт/Fixes/EmployeeChoice-fix.module.js',
   'SBIS3.EDO.FastFilters': '/usermngt/personal-office/client/Личный аккаунт/Fixes/FastFilters-fix.module.js',
   'SBIS3.EDO.FilterController': '/usermngt/personal-office/client/Личный аккаунт/Fixes/FilterController-fix.module.js',
   'SBIS3.Analytics.FinAnalysis': '/usermngt/personal-office/client/Личный аккаунт/Fixes/FinAnalysis-fix.module.js',
   'SBIS3.EDO.Filters': '/usermngt/personal-office/client/Личный аккаунт/Fixes/Filters-fix.module.js',
   'SBIS3.CRM.FixContragent': '/usermngt/personal-office/client/Личный аккаунт/Fixes/FixContragent-fix.module.js',
   'SBIS3.Contragents.ListOurOrganizationsWithoutButtons': '/usermngt/personal-office/client/Личный аккаунт/Fixes/ListOurOrganizationsWithoutButtons-fix.module.js',
   'SBIS3.Warehouse.Registry.NomenclaturePublicTab': '/usermngt/personal-office/client/Личный аккаунт/Fixes/NomenclaturePublicTab-fix.module.js',
   'SBIS3.Warehouse.NomenclatureSelection': '/usermngt/personal-office/client/Личный аккаунт/Fixes/NomenclatureSelection-fix.module.js',
   'SBIS3.PrivateFace.IndividualFaceSelection': '/usermngt/personal-office/client/Личный аккаунт/Fixes/IndividualFaceSelection-fix.module.js',
   'SBIS3.Contragents.OurCardPanel': '/usermngt/personal-office/client/Личный аккаунт/Fixes/OurCardPanel-fix.module.js',
   'SBIS3.CRM.PathFilter': '/usermngt/personal-office/client/Личный аккаунт/Fixes/PathFilter-fix.module.js',
   'SBIS3.CRM.Phone': '/usermngt/personal-office/client/Личный аккаунт/Fixes/Phone-fix.module.js',
   'SBIS3.PrivateFace.Photo': '/usermngt/personal-office/client/Личный аккаунт/Fixes/PrivateFacePhoto-fix.module.js',
   'SBIS3.CRM.PhoneCode': '/usermngt/personal-office/client/Личный аккаунт/Fixes/PhoneCode.module.js',
   'SBIS3.PrivateFace.PrivatePersonEditor': '/usermngt/personal-office/client/Личный аккаунт/Fixes/PrivatePersonEditor-fix.module.js',
   'SBIS3.Analytics.Reliability': '/usermngt/personal-office/client/Личный аккаунт/Fixes/Reliability-fix.module.js',
   'SBIS3.Employee.StaffChoice.List': '/usermngt/personal-office/client/Личный аккаунт/Fixes/StaffChoiceList-fix.module.js',
   'SBIS3.Staff.Employee': '/usermngt/personal-office/client/Личный аккаунт/Fixes/StaffEmployee-fix.module.js',
   'SBIS3.Staff.StaffFunction': '/usermngt/personal-office/client/Личный аккаунт/Fixes/StaffFuction-fix.module.js',
   'SBIS3.Staff.Photo.Control': '/usermngt/personal-office/client/Личный аккаунт/Fixes/StaffPhotoControl.module.js',
   'SBIS3.CRM.Theme': '/usermngt/personal-office/client/Личный аккаунт/Fixes/Theme-fix.module.js',
   'SBIS3.Warehouse.Registry.VendorRegistry.NomenclatureSelection': '/usermngt/personal-office/client/Личный аккаунт/Fixes/VendorRegistryNomenclatureSelection-fix.module.js',
   'SBIS3.WarehouseStats.BusinessPage': '/warehouse/stats/client/Warehouse Stats/WarehouseStats/BusinessPage.module.js',
   'SBIS3.BaseWidget.BaseFrame': '/work-time-mgmt/booking-widget/client/BaseWidget/Components/Frames/Base/BaseFrame/BaseFrame.module.js',
   'SBIS3.NAVIGATION.ProductivityConfig': '/work-time-mgmt/activity/main-service/client/UnproductiveActivity/Navigation/Navigation.module.js',
   'SBIS3.BaseWidget.BaseHeaderFrame': '/work-time-mgmt/booking-widget/client/BaseWidget/Components/Frames/Base/BaseHeaderFrame/BaseHeaderFrame.module.js',
   'SBIS3.BaseWidget.BaseListViewFrame': '/work-time-mgmt/booking-widget/client/BaseWidget/Components/Frames/Base/BaseListViewFrame/BaseListViewFrame.module.js',
   'SBIS3.BaseWidget.BasePage': '/work-time-mgmt/booking-widget/client/BaseWidget/Components/Frames/Base/BasePage/BasePage.module.js',
   'SBIS3.BaseWidget.BaseTemplateAreaFrame': '/work-time-mgmt/booking-widget/client/BaseWidget/Components/Frames/Base/BaseTemplateAreaFrame/BaseTemplateAreaFrame.module.js',
   'SBIS3.BaseWidget.ErrorFrame': '/work-time-mgmt/booking-widget/client/BaseWidget/Components/Frames/ErrorFrame/ErrorFrame.module.js',
   'SBIS3.BaseWidget.FinishFrame': '/work-time-mgmt/booking-widget/client/BaseWidget/Components/Frames/FinishFrame/FinishFrame.module.js',
   'SBIS3.BaseWidget.NomenclatureFrame': '/work-time-mgmt/booking-widget/client/BaseWidget/Components/Frames/NomenclatureOrderFrame/Components/NomenclatureFrame/NomenclatureFrame.module.js',
   'SBIS3.BaseWidget.NomenclatureListFragment': '/work-time-mgmt/booking-widget/client/BaseWidget/Components/Frames/NomenclatureOrderFrame/Components/NomenclatureListFragment/NomenclatureListFragment.module.js',
   'SBIS3.BaseWidget.NomenclatureOrderFrame': '/work-time-mgmt/booking-widget/client/BaseWidget/Components/Frames/NomenclatureOrderFrame/NomenclatureOrderFrame.module.js',
   'SBIS3.BaseWidget.OrderFragment': '/work-time-mgmt/booking-widget/client/BaseWidget/Components/Frames/NomenclatureOrderFrame/Components/OrderFragment/OrderFragment.module.js',
   'SBIS3.BaseWidget.PaymentFrame': '/work-time-mgmt/booking-widget/client/BaseWidget/Components/Frames/PaymentFrame/PaymentFrame.module.js',
   'SBIS3.BaseWidget.CustomerDetailsFrame': '/work-time-mgmt/booking-widget/client/BaseWidget/Components/Frames/CustomerDetailsFrame/CustomerDetailsFrame.module.js',
   'SBIS3.BaseWidget.PointListFrame': '/work-time-mgmt/booking-widget/client/BaseWidget/Components/Frames/PointListFrame/PointListFrame.module.js',
   'SBIS3.BaseWidget.BasketIcon': '/work-time-mgmt/booking-widget/client/BaseWidget/Components/View/BasketIcon/BasketIcon.module.js',
   'SBIS3.BaseWidget.ButtonCounterView': '/work-time-mgmt/booking-widget/client/BaseWidget/Components/View/ButtonCounterView/ButtonCounterView.module.js',
   'SBIS3.BaseWidget.Calendar': '/work-time-mgmt/booking-widget/client/BaseWidget/Components/View/Calendar/Calendar.module.js',
   'SBIS3.BaseWidget.CounterView': '/work-time-mgmt/booking-widget/client/BaseWidget/Components/View/CounterView/CounterView.module.js',
   'SBIS3.BaseWidget.PhotoView': '/work-time-mgmt/booking-widget/client/BaseWidget/Components/View/PhotoView/PhotoView.module.js',
   'SBIS3.BaseWidget.ClassUtils': '/work-time-mgmt/booking-widget/client/BaseWidget/Helpers/ClassUtils.module.js',
   'SBIS3.BaseWidget.Helpers.Constants': '/work-time-mgmt/booking-widget/client/BaseWidget/Helpers/Constants.module.js',
   'SBIS3.BaseWidget.Helpers.CommonsFunctions': '/work-time-mgmt/booking-widget/client/BaseWidget/Helpers/CommonsFunctions.module.js',
   'SBIS3.BaseWidget.OrderHelper': '/work-time-mgmt/booking-widget/client/BaseWidget/Helpers/OrderHelper.module.js',
   'SBIS3.BaseWidget.YandexMap': '/work-time-mgmt/booking-widget/client/BaseWidget/Components/View/YandexMap/YandexMap.module.js',
   'SBIS3.BaseWidget.CustomerModel': '/work-time-mgmt/booking-widget/client/BaseWidget/Model/CustomerModel.module.js',
   'SBIS3.BaseWidget.PagesHelper': '/work-time-mgmt/booking-widget/client/BaseWidget/Helpers/PagesHelper.module.js',
   'SBIS3.BaseWidget.DateTimeModel': '/work-time-mgmt/booking-widget/client/BaseWidget/Model/DateTimeModel.module.js',
   'SBIS3.BaseWidget.OrderModel': '/work-time-mgmt/booking-widget/client/BaseWidget/Model/OrderModel.module.js',
   'SBIS3.BaseWidget.NomenclatureModel': '/work-time-mgmt/booking-widget/client/BaseWidget/Model/NomenclatureModel.module.js',
   'SBIS3.BaseWidget.BaseController': '/work-time-mgmt/booking-widget/client/BaseWidget/Pages/BaseController/BaseController.module.js',
   'SBIS3.BaseWidget.PointModel': '/work-time-mgmt/booking-widget/client/BaseWidget/Model/PointModel.module.js',
   'SBIS3.BaseWidget.StepPageController': '/work-time-mgmt/booking-widget/client/BaseWidget/Pages/StepPageController/StepPageController.module.js',
   'SBIS3.BaseWidget.WidgetPageController': '/work-time-mgmt/booking-widget/client/BaseWidget/Pages/WidgetPageController/WidgetPageController.module.js',
   'SBIS3.BaseWidget.CommonValidators': '/work-time-mgmt/booking-widget/client/BaseWidget/Validators/CommonValidators.module.js',
   'SBIS3.BeautyWidget.CustomerDetailsFrame': '/work-time-mgmt/booking-widget/client/BeautyWidget/Components/Frames/CustomerDetailsFrame/CustomerDetailsFrame.module.js',
   'SBIS3.BeautyWidget.ErrorFrame': '/work-time-mgmt/booking-widget/client/BeautyWidget/Components/Frames/ErrorFrame/ErrorFrame.module.js',
   'SBIS3.BeautyWidget.PaymentFrame': '/work-time-mgmt/booking-widget/client/BeautyWidget/Components/Frames/PaymentFrame/PaymentFrame.module.js',
   'SBIS3.BeautyWidget.FinishFrame': '/work-time-mgmt/booking-widget/client/BeautyWidget/Components/Frames/FinishFrame/FinishFrame.module.js',
   'SBIS3.BeautyWidget.PointListFrame': '/work-time-mgmt/booking-widget/client/BeautyWidget/Components/Frames/PointListFrame/PointListFrame.module.js',
   'SBIS3.BeautyWidget.Helpers.CommonsFunctions': '/work-time-mgmt/booking-widget/client/BeautyWidget/Helpers/CommonsFunctions.module.js',
   'SBIS3.BeautyWidget.OrderModel': '/work-time-mgmt/booking-widget/client/BeautyWidget/Model/OrderModel.module.js',
   'SBIS3.BeautyWidget.Helpers.Constants': '/work-time-mgmt/booking-widget/client/BeautyWidget/Helpers/Constants.module.js',
   'SBIS3.BeautyWidget.PageController': '/work-time-mgmt/booking-widget/client/BeautyWidget/Pages/PageController/PageController.module.js',
   'SBIS3.PrestoWidget.CustomerDetailsFrame': '/work-time-mgmt/booking-widget/client/PrestoWidget/Components/Frames/CustomerDetailsFrame/CustomerDetailsFrame.module.js',
   'SBIS3.PrestoWidget.HallListFragment': '/work-time-mgmt/booking-widget/client/PrestoWidget/Components/Frames/DateTimeFrame/Components/HallListFragment/HallListFragment.module.js',
   'SBIS3.PrestoWidget.TableListFragment': '/work-time-mgmt/booking-widget/client/PrestoWidget/Components/Frames/DateTimeFrame/Components/TableListFragment/TableListFragment.module.js',
   'SBIS3.BeautyWidget.PointModel': '/work-time-mgmt/booking-widget/client/BeautyWidget/Model/PointModel.module.js',
   'SBIS3.BeautyWidget.Helpers.CommonsFactory': '/work-time-mgmt/booking-widget/client/BeautyWidget/Helpers/CommonsFactory.module.js',
   'SBIS3.PrestoWidget.WithoutTableFragment': '/work-time-mgmt/booking-widget/client/PrestoWidget/Components/Frames/DateTimeFrame/Components/WithoutTableFragment/WithoutTableFragment.module.js',
   'SBIS3.PrestoWidget.DishOrderFrame': '/work-time-mgmt/booking-widget/client/PrestoWidget/Components/Frames/DishOrderFrame/DishOrderFrame.module.js',
   'SBIS3.PrestoWidget.DateTimeFrame': '/work-time-mgmt/booking-widget/client/PrestoWidget/Components/Frames/DateTimeFrame/DateTimeFrame.module.js',
   'SBIS3.PrestoWidget.ErrorFrame': '/work-time-mgmt/booking-widget/client/PrestoWidget/Components/Frames/ErrorFrame/ErrorFrame.module.js',
   'SBIS3.PrestoWidget.FinishFrame': '/work-time-mgmt/booking-widget/client/PrestoWidget/Components/Frames/FinishFrame/FinishFrame.module.js',
   'SBIS3.PrestoWidget.PaymentFrame': '/work-time-mgmt/booking-widget/client/PrestoWidget/Components/Frames/PaymentFrame/PaymentFrame.module.js',
   'SBIS3.PrestoWidget.DateTextBox': '/work-time-mgmt/booking-widget/client/PrestoWidget/Components/View/DateTextBox/DateTextBox.module.js',
   'SBIS3.PrestoWidget.DateTimePicker': '/work-time-mgmt/booking-widget/client/PrestoWidget/Components/View/DateTimePicker/DateTimePicker.module.js',
   'SBIS3.PrestoWidget.RoomTable': '/work-time-mgmt/booking-widget/client/PrestoWidget/Components/View/RoomView/Components/RoomTable/RoomTable.module.js',
   'SBIS3.PrestoWidget.PointListFrame': '/work-time-mgmt/booking-widget/client/PrestoWidget/Components/Frames/PointListFrame/PointListFrame.module.js',
   'SBIS3.PrestoWidget.RoomView.Constants': '/work-time-mgmt/booking-widget/client/PrestoWidget/Components/View/RoomView/Helpers/Constants.module.js',
   'SBIS3.PrestoWidget.RoomView': '/work-time-mgmt/booking-widget/client/PrestoWidget/Components/View/RoomView/RoomView.module.js',
   'SBIS3.PrestoWidget.TimeComboBox': '/work-time-mgmt/booking-widget/client/PrestoWidget/Components/View/TimeComboBox/TimeComboBox.module.js',
   'SBIS3.PrestoWidget.AnyTableManager': '/work-time-mgmt/booking-widget/client/PrestoWidget/Helpers/AnyTableManager.module.js',
   'SBIS3.PrestoWidget.Helpers.Constants': '/work-time-mgmt/booking-widget/client/PrestoWidget/Helpers/Constants.module.js',
   'SBIS3.PrestoWidget.Helpers.CommonsFunctions': '/work-time-mgmt/booking-widget/client/PrestoWidget/Helpers/CommonsFunctions.module.js',
   'SBIS3.PrestoWidget.Helpers.Settings': '/work-time-mgmt/booking-widget/client/PrestoWidget/Helpers/Settings.module.js',
   'SBIS3.PrestoWidget.DateTimeModel': '/work-time-mgmt/booking-widget/client/PrestoWidget/Model/DateTimeModel.module.js',
   'SBIS3.PrestoWidget.HallModel': '/work-time-mgmt/booking-widget/client/PrestoWidget/Model/HallModel.module.js',
   'SBIS3.PrestoWidget.Helpers.CommonsFactory': '/work-time-mgmt/booking-widget/client/PrestoWidget/Helpers/CommonsFactory.module.js',
   'SBIS3.PrestoWidget.DishModel': '/work-time-mgmt/booking-widget/client/PrestoWidget/Model/DishModel.module.js',
   'SBIS3.PrestoWidget.OrderModel': '/work-time-mgmt/booking-widget/client/PrestoWidget/Model/OrderModel.module.js',
   'SBIS3.PrestoWidget.TableModel': '/work-time-mgmt/booking-widget/client/PrestoWidget/Model/TableModel.module.js',
   'SBIS3.PrestoWidget.PointModel': '/work-time-mgmt/booking-widget/client/PrestoWidget/Model/PointModel.module.js',
   'SBIS3.PrestoWidget.ErrorController': '/work-time-mgmt/booking-widget/client/PrestoWidget/Pages/ErrorController/ErrorController.module.js',
   'SBIS3.PrestoWidget.FinishController': '/work-time-mgmt/booking-widget/client/PrestoWidget/Pages/FinishController/FinishController.module.js',
   'SBIS3.PrestoWidget.PageController': '/work-time-mgmt/booking-widget/client/PrestoWidget/Pages/PageController/PageController.module.js',
   'SBIS3.ThemeBookingWidget.Constants': '/work-time-mgmt/booking-widget/client/ThemeBookingWidget/Helpers/Constants.module.js',
   'SBIS3.PrestoWidget.SinglePageController': '/work-time-mgmt/booking-widget/client/PrestoWidget/Pages/SinglePageController/SinglePageController.module.js',
   'SBIS3.ThemeBookingWidget.ControllerFactory': '/work-time-mgmt/booking-widget/client/ThemeBookingWidget/Helpers/ControllerFactory.module.js',
   'SBIS3.BookingWidget.View': '/work-time-mgmt/booking-widget/client/ThemeBookingWidget/View/View.module.js',
   'SBIS3.ThemeBookingWidget.RenderHelper': '/work-time-mgmt/booking-widget/client/ThemeBookingWidget/Helpers/RenderHelper.module.js',
   'SBIS3.CALENDAR.CalendarInAccordion.FieldDatePickerCalendarHandlers': '/work-time-mgmt/event-calendar/client-my/MainUserCalendar/Deprecated/FieldDatePickerCalendarHandlers.module.js'
};
